export const widgetTokens = {
	radius: {
		base: "0.5rem",
		sm: "calc(var(--radius) - 4px)",
		md: "calc(var(--radius) - 2px)",
		lg: "var(--radius)",
		xl: "calc(var(--radius) + 4px)",
		"2xl": "calc(var(--radius) + 8px)",
		"3xl": "calc(var(--radius) + 12px)",
	},
	cssRadius: {
		"2xs": "0.125rem",
		xs: "0.25rem",
		sm: "0.375rem",
		md: "0.5rem",
		lg: "0.625rem",
		xl: "0.75rem",
		"2xl": "1rem",
		"3xl": "1.25rem",
		"4xl": "1.5rem",
		full: "9999px",
	},
	typography: {
		bodySize: "14px",
		bodyLineHeight: "1.5",
		weightNormal: 400,
		weightMedium: 500,
		weightSemibold: 600,
		weightBold: 700,
	},
	control: {
		heightXs: "1.75rem",
		heightSm: "2.25rem",
		heightMd: "2.5rem",
		heightLg: "2.75rem",
		heightCta: "3rem",
		paddingXxs: "0.625rem",
		paddingXsm: "0.75rem",
		paddingXmd: "0.875rem",
		paddingXlg: "1rem",
		paddingXcta: "1.25rem",
		gapXs: "0.25rem",
		gapSm: "0.25rem",
		gapMd: "0.375rem",
		gapLg: "0.5rem",
		touchTarget: "2.75rem",
		iconXs: "0.875rem",
		iconSm: "1rem",
		iconMd: "1.125rem",
		iconLg: "1.25rem",
	},
	icon: {
		xs: "0.75rem",
		sm: "1rem",
		md: "1.25rem",
		lg: "1.5rem",
		xl: "2rem",
		"2xl": "2.5rem",
		"3xl": "3rem",
	},
	semanticNames: [
		"background",
		"foreground",
		"card",
		"muted",
		"primary",
		"secondary",
		"accent",
		"destructive",
		"border",
		"ring",
	] as const,
} as const;

export const widgetCssVariables = {
	radius: {
		base: widgetTokens.radius.base,
		"2xs": widgetTokens.cssRadius["2xs"],
		xs: widgetTokens.cssRadius.xs,
		sm: widgetTokens.cssRadius.sm,
		md: widgetTokens.cssRadius.md,
		lg: widgetTokens.cssRadius.lg,
		xl: widgetTokens.cssRadius.xl,
		"2xl": widgetTokens.cssRadius["2xl"],
		"3xl": widgetTokens.cssRadius["3xl"],
		"4xl": widgetTokens.cssRadius["4xl"],
		full: widgetTokens.cssRadius.full,
	},
	fontWeight: {
		normal: widgetTokens.typography.weightNormal,
		medium: widgetTokens.typography.weightMedium,
		semibold: widgetTokens.typography.weightSemibold,
		bold: widgetTokens.typography.weightBold,
	},
	control: {
		heightXs: widgetTokens.control.heightXs,
		heightSm: widgetTokens.control.heightSm,
		heightMd: widgetTokens.control.heightMd,
		heightLg: widgetTokens.control.heightLg,
		heightCta: widgetTokens.control.heightCta,
		paddingXxs: widgetTokens.control.paddingXxs,
		paddingXsm: widgetTokens.control.paddingXsm,
		paddingXmd: widgetTokens.control.paddingXmd,
		paddingXlg: widgetTokens.control.paddingXlg,
		paddingXcta: widgetTokens.control.paddingXcta,
		gapXs: widgetTokens.control.gapXs,
		gapSm: widgetTokens.control.gapSm,
		gapMd: widgetTokens.control.gapMd,
		gapLg: widgetTokens.control.gapLg,
		touchTarget: widgetTokens.control.touchTarget,
		iconXs: widgetTokens.control.iconXs,
		iconSm: widgetTokens.control.iconSm,
		iconMd: widgetTokens.control.iconMd,
		iconLg: widgetTokens.control.iconLg,
	},
	icon: {
		xs: widgetTokens.icon.xs,
		sm: widgetTokens.icon.sm,
		md: widgetTokens.icon.md,
		lg: widgetTokens.icon.lg,
		xl: widgetTokens.icon.xl,
		"2xl": widgetTokens.icon["2xl"],
		"3xl": widgetTokens.icon["3xl"],
	},
} as const;

export const widgetHostCssVariables = {
	radius: {
		"--border-radius-full": widgetCssVariables.radius.full,
		"--border-radius-lg": widgetCssVariables.radius.lg,
		"--border-radius-md": widgetCssVariables.radius.md,
		"--border-radius-sm": widgetCssVariables.radius.sm,
		"--border-radius-xl": widgetCssVariables.radius.xl,
		"--border-radius-xs": widgetCssVariables.radius.xs,
	},
	fontWeight: {
		"--font-weight-bold": String(widgetCssVariables.fontWeight.bold),
		"--font-weight-medium": String(widgetCssVariables.fontWeight.medium),
		"--font-weight-normal": String(widgetCssVariables.fontWeight.normal),
		"--font-weight-semibold": String(widgetCssVariables.fontWeight.semibold),
	},
} as const;

export type WidgetTokens = typeof widgetTokens;
export type WidgetCssVariables = typeof widgetCssVariables;
export type WidgetHostCssVariables = typeof widgetHostCssVariables;
