INSERT INTO app_tools (
	id,
	app_id,
	tool_type_id,
	tool_id,
	title,
	description,
	input_schema,
	output_schema,
	adapter_scope,
	result_strategy,
	auth_required,
	visibility,
	annotations,
	config,
	schema_dialect,
	schema_source,
	schema_source_ref,
	enabled,
	sort_order,
	created_at,
	updated_at
)
SELECT
	'392afcee-06cb-440b-9038-ddf3979bb36e',
	apps.id,
	'rpc',
	'get_billing_overview',
	'Get Billing Overview',
	'Tedix oRPC endpoint billing/getOverview',
	'{"type":"object","properties":{},"additionalProperties":false}',
	'{"type":"object","additionalProperties":true}',
	'primary',
	'merge',
	1,
	'private',
	'{"readOnlyHint":true,"destructiveHint":false,"idempotentHint":true,"openWorldHint":false}',
	'{"transport":"rpc","endpoint":"billing/getOverview","responsePath":"json","method":"GET"}',
	'json-schema-2020-12',
	'orpc',
	'billing/getOverview',
	1,
	0,
	CURRENT_TIMESTAMP,
	CURRENT_TIMESTAMP
FROM apps
WHERE apps.slug = 'tedix'
ON CONFLICT(app_id, tool_id) DO UPDATE SET
	title = excluded.title,
	description = excluded.description,
	config = excluded.config,
	schema_dialect = excluded.schema_dialect,
	schema_source = excluded.schema_source,
	schema_source_ref = excluded.schema_source_ref,
	auth_required = excluded.auth_required,
	visibility = excluded.visibility,
	annotations = excluded.annotations,
	enabled = excluded.enabled,
	updated_at = CURRENT_TIMESTAMP;
