/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as CliSessionRouteImport } from './routes/_cli-session'
import { Route as SessionRouteImport } from './routes/_session'
import { Route as AuthInviteRouteImport } from './routes/_auth.invite'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as SessionChromeFreeRouteImport } from './routes/_session/_chrome-free'
import { Route as SessionTenantRouteImport } from './routes/_session/_tenant'
import { Route as SessionAccountRouteImport } from './routes/_session/account'
import { Route as AuthOauthConsentRouteImport } from './routes/_auth.oauth.consent'
import { Route as CliSessionCliLoginRouteImport } from './routes/_cli-session/cli/login'
import { Route as SessionChromeFreeSharedRouteImport } from './routes/_session/_chrome-free/shared'
import { Route as SessionTenantIndexRouteImport } from './routes/_session/_tenant/index'
import { Route as SessionTenantAdminRouteImport } from './routes/_session/_tenant/admin'
import { Route as SessionTenantAppsRouteImport } from './routes/_session/_tenant/apps'
import { Route as SessionTenantAuditRouteImport } from './routes/_session/_tenant/audit'
import { Route as SessionTenantBlueprintsRouteImport } from './routes/_session/_tenant/blueprints'
import { Route as SessionTenantBrainRouteImport } from './routes/_session/_tenant/brain'
import { Route as SessionTenantChatRouteImport } from './routes/_session/_tenant/chat'
import { Route as SessionTenantComputeRouteImport } from './routes/_session/_tenant/compute'
import { Route as SessionTenantGatewaysRouteImport } from './routes/_session/_tenant/gateways'
import { Route as SessionTenantInstallRouteImport } from './routes/_session/_tenant/install'
import { Route as SessionTenantOutputsRouteImport } from './routes/_session/_tenant/outputs'
import { Route as SessionTenantSitesRouteImport } from './routes/_session/_tenant/sites'
import { Route as SessionTenantSkillsRouteImport } from './routes/_session/_tenant/skills'
import { Route as SessionTenantTeamRouteImport } from './routes/_session/_tenant/team'
import { Route as SessionTenantWidgetRouteImport } from './routes/_session/_tenant/widget'
import { Route as SessionTenantWorkRouteImport } from './routes/_session/_tenant/work'
import { Route as SessionTenantWorkspacesRouteImport } from './routes/_session/_tenant/workspaces'
import { Route as SessionAccountAuthorizationsRouteImport } from './routes/_session/account/authorizations'
import { Route as SessionAccountOnboardingRouteImport } from './routes/_session/account/onboarding'
import { Route as SessionAccountOrganizationsRouteImport } from './routes/_session/account/organizations'
import { Route as SessionAccountProfileRouteImport } from './routes/_session/account/profile'
import { Route as SessionChromeFreeOauthCallbackRouteImport } from './routes/_session/_chrome-free/oauth.callback'
import { Route as SessionChromeFreeWorkspaceWorkspaceIdRouteImport } from './routes/_session/_chrome-free/workspace_.$workspaceId'
import { Route as SessionTenantAccountConnectionsRouteImport } from './routes/_session/_tenant/account.connections'
import { Route as SessionTenantAccountSettingsRouteImport } from './routes/_session/_tenant/account.settings'
import { Route as SessionTenantAdminIndexRouteImport } from './routes/_session/_tenant/admin.index'
import { Route as SessionTenantAdminApiKeysRouteImport } from './routes/_session/_tenant/admin.api-keys'
import { Route as SessionTenantAdminBillingRouteImport } from './routes/_session/_tenant/admin.billing'
import { Route as SessionTenantAdminConnectionsRouteImport } from './routes/_session/_tenant/admin.connections'
import { Route as SessionTenantAdminOrganizationRouteImport } from './routes/_session/_tenant/admin.organization'
import { Route as SessionTenantAdminPaymentsRouteImport } from './routes/_session/_tenant/admin.payments'
import { Route as SessionTenantAppsAppIdRouteImport } from './routes/_session/_tenant/apps_.$appId'
import { Route as SessionTenantExploreAppsRouteImport } from './routes/_session/_tenant/explore.apps'
import { Route as SessionTenantOutputsOutputIdRouteImport } from './routes/_session/_tenant/outputs_.$outputId'
import { Route as SessionTenantSkillsIndexRouteImport } from './routes/_session/_tenant/skills.index'
import { Route as SessionTenantSkillsSkillIdRouteImport } from './routes/_session/_tenant/skills.$skillId'
import { Route as SessionTenantTeamTediIdRouteImport } from './routes/_session/_tenant/team_.$tediId'
import { Route as SessionTenantTeamNewRouteImport } from './routes/_session/_tenant/team_.new'
import { Route as SessionTenantWorkIndexRouteImport } from './routes/_session/_tenant/work.index'
import { Route as SessionTenantWorkAdmissionRouteImport } from './routes/_session/_tenant/work.admission'
import { Route as SessionTenantWorkAgentsRouteImport } from './routes/_session/_tenant/work.agents'
import { Route as SessionTenantWorkApprovalsRouteImport } from './routes/_session/_tenant/work.approvals'
import { Route as SessionTenantWorkAttemptsRouteImport } from './routes/_session/_tenant/work.attempts'
import { Route as SessionTenantWorkCapacityRouteImport } from './routes/_session/_tenant/work.capacity'
import { Route as SessionTenantWorkCasesRouteImport } from './routes/_session/_tenant/work.cases'
import { Route as SessionTenantWorkClustersRouteImport } from './routes/_session/_tenant/work.clusters'
import { Route as SessionTenantWorkControlRouteImport } from './routes/_session/_tenant/work.control'
import { Route as SessionTenantWorkGraphRouteImport } from './routes/_session/_tenant/work.graph'
import { Route as SessionTenantWorkInteractionsRouteImport } from './routes/_session/_tenant/work.interactions'
import { Route as SessionTenantWorkOfficeRouteImport } from './routes/_session/_tenant/work.office'
import { Route as SessionTenantWorkPortfolioRouteImport } from './routes/_session/_tenant/work.portfolio'
import { Route as SessionTenantWorkQueueRouteImport } from './routes/_session/_tenant/work.queue'
import { Route as SessionTenantWorkRecoveryRouteImport } from './routes/_session/_tenant/work.recovery'
import { Route as SessionTenantAppsAppIdIndexRouteImport } from './routes/_session/_tenant/apps_.$appId.index'
import { Route as SessionTenantAppsAppIdAnalyticsRouteImport } from './routes/_session/_tenant/apps_.$appId.analytics'
import { Route as SessionTenantAppsAppIdContentRouteImport } from './routes/_session/_tenant/apps_.$appId.content'
import { Route as SessionTenantAppsAppIdSettingsRouteImport } from './routes/_session/_tenant/apps_.$appId.settings'
import { Route as SessionTenantAppsAppIdToolsRouteImport } from './routes/_session/_tenant/apps_.$appId.tools'
import { Route as SessionTenantExploreAppsSlugRouteImport } from './routes/_session/_tenant/explore.apps_.$slug'
import { Route as SessionTenantSkillsSkillIdIndexRouteImport } from './routes/_session/_tenant/skills.$skillId.index'
import { Route as SessionTenantSkillsSkillIdRunsRouteImport } from './routes/_session/_tenant/skills.$skillId.runs'
import { Route as SessionTenantSkillsSkillIdScheduleRouteImport } from './routes/_session/_tenant/skills.$skillId.schedule'
import { Route as SessionTenantSkillsSkillIdVersionsRouteImport } from './routes/_session/_tenant/skills.$skillId.versions'
import { Route as SessionTenantTeamTediIdIndexRouteImport } from './routes/_session/_tenant/team_.$tediId.index'
import { Route as SessionTenantTeamTediIdAuthorityRouteImport } from './routes/_session/_tenant/team_.$tediId.authority'
import { Route as SessionTenantTeamTediIdLearningRouteImport } from './routes/_session/_tenant/team_.$tediId.learning'
import { Route as SessionTenantTeamTediIdMemoryRouteImport } from './routes/_session/_tenant/team_.$tediId.memory'
import { Route as SessionTenantTeamTediIdSettingsRouteImport } from './routes/_session/_tenant/team_.$tediId.settings'
import { Route as SessionTenantTeamTediIdTelemetryRouteImport } from './routes/_session/_tenant/team_.$tediId.telemetry'
import { Route as SessionTenantWorkCasesCaseIdRouteImport } from './routes/_session/_tenant/work.cases.$caseId'
import { Route as SessionTenantWorkExecutionsRunIdRouteImport } from './routes/_session/_tenant/work.executions.$runId'
import { Route as SessionTenantWorkInteractionsRequestIdRouteImport } from './routes/_session/_tenant/work.interactions.$requestId'
import { Route as SessionTenantWorkItemsWorkItemIdRouteImport } from './routes/_session/_tenant/work.items.$workItemId'
import { Route as SessionTenantWorkProjectsProjectIdRouteImport } from './routes/_session/_tenant/work.projects.$projectId'
import { Route as SessionTenantWorkRunsRunIdRouteImport } from './routes/_session/_tenant/work.runs.$runId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CliSessionRoute = CliSessionRouteImport.update({
  id: '/_cli-session',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/_session',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInviteRoute = AuthInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const SessionChromeFreeRoute = SessionChromeFreeRouteImport.update({
  id: '/_chrome-free',
  getParentRoute: () => SessionRoute,
} as any)
const SessionTenantRoute = SessionTenantRouteImport.update({
  id: '/_tenant',
  getParentRoute: () => SessionRoute,
} as any)
const SessionAccountRoute = SessionAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SessionRoute,
} as any)
const AuthOauthConsentRoute = AuthOauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => AuthRoute,
} as any)
const CliSessionCliLoginRoute = CliSessionCliLoginRouteImport.update({
  id: '/cli/login',
  path: '/cli/login',
  getParentRoute: () => CliSessionRoute,
} as any)
const SessionChromeFreeSharedRoute = SessionChromeFreeSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => SessionChromeFreeRoute,
} as any)
const SessionTenantIndexRoute = SessionTenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantAdminRoute = SessionTenantAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantAppsRoute = SessionTenantAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantAuditRoute = SessionTenantAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantBlueprintsRoute = SessionTenantBlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantBrainRoute = SessionTenantBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantChatRoute = SessionTenantChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantComputeRoute = SessionTenantComputeRouteImport.update({
  id: '/compute',
  path: '/compute',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantGatewaysRoute = SessionTenantGatewaysRouteImport.update({
  id: '/gateways',
  path: '/gateways',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantInstallRoute = SessionTenantInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantOutputsRoute = SessionTenantOutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantSitesRoute = SessionTenantSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantSkillsRoute = SessionTenantSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantTeamRoute = SessionTenantTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantWidgetRoute = SessionTenantWidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantWorkRoute = SessionTenantWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantWorkspacesRoute = SessionTenantWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionAccountAuthorizationsRoute =
  SessionAccountAuthorizationsRouteImport.update({
    id: '/authorizations',
    path: '/authorizations',
    getParentRoute: () => SessionAccountRoute,
  } as any)
const SessionAccountOnboardingRoute =
  SessionAccountOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => SessionAccountRoute,
  } as any)
const SessionAccountOrganizationsRoute =
  SessionAccountOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => SessionAccountRoute,
  } as any)
const SessionAccountProfileRoute = SessionAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SessionAccountRoute,
} as any)
const SessionChromeFreeOauthCallbackRoute =
  SessionChromeFreeOauthCallbackRouteImport.update({
    id: '/oauth/callback',
    path: '/oauth/callback',
    getParentRoute: () => SessionChromeFreeRoute,
  } as any)
const SessionChromeFreeWorkspaceWorkspaceIdRoute =
  SessionChromeFreeWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace_/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => SessionChromeFreeRoute,
  } as any)
const SessionTenantAccountConnectionsRoute =
  SessionTenantAccountConnectionsRouteImport.update({
    id: '/account/connections',
    path: '/account/connections',
    getParentRoute: () => SessionTenantRoute,
  } as any)
const SessionTenantAccountSettingsRoute =
  SessionTenantAccountSettingsRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => SessionTenantRoute,
  } as any)
const SessionTenantAdminIndexRoute = SessionTenantAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionTenantAdminRoute,
} as any)
const SessionTenantAdminApiKeysRoute =
  SessionTenantAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => SessionTenantAdminRoute,
  } as any)
const SessionTenantAdminBillingRoute =
  SessionTenantAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => SessionTenantAdminRoute,
  } as any)
const SessionTenantAdminConnectionsRoute =
  SessionTenantAdminConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => SessionTenantAdminRoute,
  } as any)
const SessionTenantAdminOrganizationRoute =
  SessionTenantAdminOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => SessionTenantAdminRoute,
  } as any)
const SessionTenantAdminPaymentsRoute =
  SessionTenantAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => SessionTenantAdminRoute,
  } as any)
const SessionTenantAppsAppIdRoute = SessionTenantAppsAppIdRouteImport.update({
  id: '/apps_/$appId',
  path: '/apps/$appId',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantExploreAppsRoute =
  SessionTenantExploreAppsRouteImport.update({
    id: '/explore/apps',
    path: '/explore/apps',
    getParentRoute: () => SessionTenantRoute,
  } as any)
const SessionTenantOutputsOutputIdRoute =
  SessionTenantOutputsOutputIdRouteImport.update({
    id: '/outputs_/$outputId',
    path: '/outputs/$outputId',
    getParentRoute: () => SessionTenantRoute,
  } as any)
const SessionTenantSkillsIndexRoute =
  SessionTenantSkillsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SessionTenantSkillsRoute,
  } as any)
const SessionTenantSkillsSkillIdRoute =
  SessionTenantSkillsSkillIdRouteImport.update({
    id: '/$skillId',
    path: '/$skillId',
    getParentRoute: () => SessionTenantSkillsRoute,
  } as any)
const SessionTenantTeamTediIdRoute = SessionTenantTeamTediIdRouteImport.update({
  id: '/team_/$tediId',
  path: '/team/$tediId',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantTeamNewRoute = SessionTenantTeamNewRouteImport.update({
  id: '/team_/new',
  path: '/team/new',
  getParentRoute: () => SessionTenantRoute,
} as any)
const SessionTenantWorkIndexRoute = SessionTenantWorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionTenantWorkRoute,
} as any)
const SessionTenantWorkAdmissionRoute =
  SessionTenantWorkAdmissionRouteImport.update({
    id: '/admission',
    path: '/admission',
    getParentRoute: () => SessionTenantWorkRoute,
  } as any)
const SessionTenantWorkAgentsRoute = SessionTenantWorkAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => SessionTenantWorkRoute,
} as any)
const SessionTenantWorkApprovalsRoute =
  SessionTenantWorkApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => SessionTenantWorkRoute,
  } as any)
const SessionTenantWorkAttemptsRoute =
  SessionTenantWorkAttemptsRouteImport.update({
    id: '/attempts',
    path: '/attempts',
    getParentRoute: () => SessionTenantWorkRoute,
  } as any)
const SessionTenantWorkCapacityRoute =
  SessionTenantWorkCapacityRouteImport.update({
    id: '/capacity',
    path: '/capacity',
    getParentRoute: () => SessionTenantWorkRoute,
  } as any)
const SessionTenantWorkCasesRoute = SessionTenantWorkCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => SessionTenantWorkRoute,
} as any)
const SessionTenantWorkClustersRoute =
  SessionTenantWorkClustersRouteImport.update({
    id: '/clusters',
    path: '/clusters',
    getParentRoute: () => SessionTenantWorkRoute,
  } as any)
const SessionTenantWorkControlRoute =
  SessionTenantWorkControlRouteImport.update({
    id: '/control',
    path: '/control',
    getParentRoute: () => SessionTenantWorkRoute,
  } as any)
const SessionTenantWorkGraphRoute = SessionTenantWorkGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => SessionTenantWorkRoute,
} as any)
const SessionTenantWorkInteractionsRoute =
  SessionTenantWorkInteractionsRouteImport.update({
    id: '/interactions',
    path: '/interactions',
    getParentRoute: () => SessionTenantWorkRoute,
  } as any)
const SessionTenantWorkOfficeRoute = SessionTenantWorkOfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => SessionTenantWorkRoute,
} as any)
const SessionTenantWorkPortfolioRoute =
  SessionTenantWorkPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => SessionTenantWorkRoute,
  } as any)
const SessionTenantWorkQueueRoute = SessionTenantWorkQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => SessionTenantWorkRoute,
} as any)
const SessionTenantWorkRecoveryRoute =
  SessionTenantWorkRecoveryRouteImport.update({
    id: '/recovery',
    path: '/recovery',
    getParentRoute: () => SessionTenantWorkRoute,
  } as any)
const SessionTenantAppsAppIdIndexRoute =
  SessionTenantAppsAppIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SessionTenantAppsAppIdRoute,
  } as any)
const SessionTenantAppsAppIdAnalyticsRoute =
  SessionTenantAppsAppIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => SessionTenantAppsAppIdRoute,
  } as any)
const SessionTenantAppsAppIdContentRoute =
  SessionTenantAppsAppIdContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => SessionTenantAppsAppIdRoute,
  } as any)
const SessionTenantAppsAppIdSettingsRoute =
  SessionTenantAppsAppIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => SessionTenantAppsAppIdRoute,
  } as any)
const SessionTenantAppsAppIdToolsRoute =
  SessionTenantAppsAppIdToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => SessionTenantAppsAppIdRoute,
  } as any)
const SessionTenantExploreAppsSlugRoute =
  SessionTenantExploreAppsSlugRouteImport.update({
    id: '/explore/apps_/$slug',
    path: '/explore/apps/$slug',
    getParentRoute: () => SessionTenantRoute,
  } as any)
const SessionTenantSkillsSkillIdIndexRoute =
  SessionTenantSkillsSkillIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SessionTenantSkillsSkillIdRoute,
  } as any)
const SessionTenantSkillsSkillIdRunsRoute =
  SessionTenantSkillsSkillIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => SessionTenantSkillsSkillIdRoute,
  } as any)
const SessionTenantSkillsSkillIdScheduleRoute =
  SessionTenantSkillsSkillIdScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => SessionTenantSkillsSkillIdRoute,
  } as any)
const SessionTenantSkillsSkillIdVersionsRoute =
  SessionTenantSkillsSkillIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => SessionTenantSkillsSkillIdRoute,
  } as any)
const SessionTenantTeamTediIdIndexRoute =
  SessionTenantTeamTediIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SessionTenantTeamTediIdRoute,
  } as any)
const SessionTenantTeamTediIdAuthorityRoute =
  SessionTenantTeamTediIdAuthorityRouteImport.update({
    id: '/authority',
    path: '/authority',
    getParentRoute: () => SessionTenantTeamTediIdRoute,
  } as any)
const SessionTenantTeamTediIdLearningRoute =
  SessionTenantTeamTediIdLearningRouteImport.update({
    id: '/learning',
    path: '/learning',
    getParentRoute: () => SessionTenantTeamTediIdRoute,
  } as any)
const SessionTenantTeamTediIdMemoryRoute =
  SessionTenantTeamTediIdMemoryRouteImport.update({
    id: '/memory',
    path: '/memory',
    getParentRoute: () => SessionTenantTeamTediIdRoute,
  } as any)
const SessionTenantTeamTediIdSettingsRoute =
  SessionTenantTeamTediIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => SessionTenantTeamTediIdRoute,
  } as any)
const SessionTenantTeamTediIdTelemetryRoute =
  SessionTenantTeamTediIdTelemetryRouteImport.update({
    id: '/telemetry',
    path: '/telemetry',
    getParentRoute: () => SessionTenantTeamTediIdRoute,
  } as any)
const SessionTenantWorkCasesCaseIdRoute =
  SessionTenantWorkCasesCaseIdRouteImport.update({
    id: '/$caseId',
    path: '/$caseId',
    getParentRoute: () => SessionTenantWorkCasesRoute,
  } as any)
const SessionTenantWorkExecutionsRunIdRoute =
  SessionTenantWorkExecutionsRunIdRouteImport.update({
    id: '/executions/$runId',
    path: '/executions/$runId',
    getParentRoute: () => SessionTenantWorkRoute,
  } as any)
const SessionTenantWorkInteractionsRequestIdRoute =
  SessionTenantWorkInteractionsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => SessionTenantWorkInteractionsRoute,
  } as any)
const SessionTenantWorkItemsWorkItemIdRoute =
  SessionTenantWorkItemsWorkItemIdRouteImport.update({
    id: '/items/$workItemId',
    path: '/items/$workItemId',
    getParentRoute: () => SessionTenantWorkRoute,
  } as any)
const SessionTenantWorkProjectsProjectIdRoute =
  SessionTenantWorkProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => SessionTenantWorkRoute,
  } as any)
const SessionTenantWorkRunsRunIdRoute =
  SessionTenantWorkRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => SessionTenantWorkRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SessionTenantIndexRoute
  '/invite': typeof AuthInviteRoute
  '/login': typeof AuthLoginRoute
  '/account': typeof SessionAccountRouteWithChildren
  '/oauth/consent': typeof AuthOauthConsentRoute
  '/cli/login': typeof CliSessionCliLoginRoute
  '/shared': typeof SessionChromeFreeSharedRoute
  '/admin': typeof SessionTenantAdminRouteWithChildren
  '/apps': typeof SessionTenantAppsRoute
  '/audit': typeof SessionTenantAuditRoute
  '/blueprints': typeof SessionTenantBlueprintsRoute
  '/brain': typeof SessionTenantBrainRoute
  '/chat': typeof SessionTenantChatRoute
  '/compute': typeof SessionTenantComputeRoute
  '/gateways': typeof SessionTenantGatewaysRoute
  '/install': typeof SessionTenantInstallRoute
  '/outputs': typeof SessionTenantOutputsRoute
  '/sites': typeof SessionTenantSitesRoute
  '/skills': typeof SessionTenantSkillsRouteWithChildren
  '/team': typeof SessionTenantTeamRoute
  '/widget': typeof SessionTenantWidgetRoute
  '/work': typeof SessionTenantWorkRouteWithChildren
  '/workspaces': typeof SessionTenantWorkspacesRoute
  '/account/authorizations': typeof SessionAccountAuthorizationsRoute
  '/account/onboarding': typeof SessionAccountOnboardingRoute
  '/account/organizations': typeof SessionAccountOrganizationsRoute
  '/account/profile': typeof SessionAccountProfileRoute
  '/oauth/callback': typeof SessionChromeFreeOauthCallbackRoute
  '/workspace/$workspaceId': typeof SessionChromeFreeWorkspaceWorkspaceIdRoute
  '/account/connections': typeof SessionTenantAccountConnectionsRoute
  '/account/settings': typeof SessionTenantAccountSettingsRoute
  '/admin/api-keys': typeof SessionTenantAdminApiKeysRoute
  '/admin/billing': typeof SessionTenantAdminBillingRoute
  '/admin/connections': typeof SessionTenantAdminConnectionsRoute
  '/admin/organization': typeof SessionTenantAdminOrganizationRoute
  '/admin/payments': typeof SessionTenantAdminPaymentsRoute
  '/apps/$appId': typeof SessionTenantAppsAppIdRouteWithChildren
  '/explore/apps': typeof SessionTenantExploreAppsRoute
  '/outputs/$outputId': typeof SessionTenantOutputsOutputIdRoute
  '/skills/$skillId': typeof SessionTenantSkillsSkillIdRouteWithChildren
  '/team/$tediId': typeof SessionTenantTeamTediIdRouteWithChildren
  '/team/new': typeof SessionTenantTeamNewRoute
  '/work/admission': typeof SessionTenantWorkAdmissionRoute
  '/work/agents': typeof SessionTenantWorkAgentsRoute
  '/work/approvals': typeof SessionTenantWorkApprovalsRoute
  '/work/attempts': typeof SessionTenantWorkAttemptsRoute
  '/work/capacity': typeof SessionTenantWorkCapacityRoute
  '/work/cases': typeof SessionTenantWorkCasesRouteWithChildren
  '/work/clusters': typeof SessionTenantWorkClustersRoute
  '/work/control': typeof SessionTenantWorkControlRoute
  '/work/graph': typeof SessionTenantWorkGraphRoute
  '/work/interactions': typeof SessionTenantWorkInteractionsRouteWithChildren
  '/work/office': typeof SessionTenantWorkOfficeRoute
  '/work/portfolio': typeof SessionTenantWorkPortfolioRoute
  '/work/queue': typeof SessionTenantWorkQueueRoute
  '/work/recovery': typeof SessionTenantWorkRecoveryRoute
  '/admin/': typeof SessionTenantAdminIndexRoute
  '/skills/': typeof SessionTenantSkillsIndexRoute
  '/work/': typeof SessionTenantWorkIndexRoute
  '/apps/$appId/analytics': typeof SessionTenantAppsAppIdAnalyticsRoute
  '/apps/$appId/content': typeof SessionTenantAppsAppIdContentRoute
  '/apps/$appId/settings': typeof SessionTenantAppsAppIdSettingsRoute
  '/apps/$appId/tools': typeof SessionTenantAppsAppIdToolsRoute
  '/explore/apps/$slug': typeof SessionTenantExploreAppsSlugRoute
  '/skills/$skillId/runs': typeof SessionTenantSkillsSkillIdRunsRoute
  '/skills/$skillId/schedule': typeof SessionTenantSkillsSkillIdScheduleRoute
  '/skills/$skillId/versions': typeof SessionTenantSkillsSkillIdVersionsRoute
  '/team/$tediId/authority': typeof SessionTenantTeamTediIdAuthorityRoute
  '/team/$tediId/learning': typeof SessionTenantTeamTediIdLearningRoute
  '/team/$tediId/memory': typeof SessionTenantTeamTediIdMemoryRoute
  '/team/$tediId/settings': typeof SessionTenantTeamTediIdSettingsRoute
  '/team/$tediId/telemetry': typeof SessionTenantTeamTediIdTelemetryRoute
  '/work/cases/$caseId': typeof SessionTenantWorkCasesCaseIdRoute
  '/work/executions/$runId': typeof SessionTenantWorkExecutionsRunIdRoute
  '/work/interactions/$requestId': typeof SessionTenantWorkInteractionsRequestIdRoute
  '/work/items/$workItemId': typeof SessionTenantWorkItemsWorkItemIdRoute
  '/work/projects/$projectId': typeof SessionTenantWorkProjectsProjectIdRoute
  '/work/runs/$runId': typeof SessionTenantWorkRunsRunIdRoute
  '/apps/$appId/': typeof SessionTenantAppsAppIdIndexRoute
  '/skills/$skillId/': typeof SessionTenantSkillsSkillIdIndexRoute
  '/team/$tediId/': typeof SessionTenantTeamTediIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SessionTenantIndexRoute
  '/invite': typeof AuthInviteRoute
  '/login': typeof AuthLoginRoute
  '/account': typeof SessionAccountRouteWithChildren
  '/oauth/consent': typeof AuthOauthConsentRoute
  '/cli/login': typeof CliSessionCliLoginRoute
  '/shared': typeof SessionChromeFreeSharedRoute
  '/apps': typeof SessionTenantAppsRoute
  '/audit': typeof SessionTenantAuditRoute
  '/blueprints': typeof SessionTenantBlueprintsRoute
  '/brain': typeof SessionTenantBrainRoute
  '/chat': typeof SessionTenantChatRoute
  '/compute': typeof SessionTenantComputeRoute
  '/gateways': typeof SessionTenantGatewaysRoute
  '/install': typeof SessionTenantInstallRoute
  '/outputs': typeof SessionTenantOutputsRoute
  '/sites': typeof SessionTenantSitesRoute
  '/team': typeof SessionTenantTeamRoute
  '/widget': typeof SessionTenantWidgetRoute
  '/workspaces': typeof SessionTenantWorkspacesRoute
  '/account/authorizations': typeof SessionAccountAuthorizationsRoute
  '/account/onboarding': typeof SessionAccountOnboardingRoute
  '/account/organizations': typeof SessionAccountOrganizationsRoute
  '/account/profile': typeof SessionAccountProfileRoute
  '/oauth/callback': typeof SessionChromeFreeOauthCallbackRoute
  '/workspace/$workspaceId': typeof SessionChromeFreeWorkspaceWorkspaceIdRoute
  '/account/connections': typeof SessionTenantAccountConnectionsRoute
  '/account/settings': typeof SessionTenantAccountSettingsRoute
  '/admin/api-keys': typeof SessionTenantAdminApiKeysRoute
  '/admin/billing': typeof SessionTenantAdminBillingRoute
  '/admin/connections': typeof SessionTenantAdminConnectionsRoute
  '/admin/organization': typeof SessionTenantAdminOrganizationRoute
  '/admin/payments': typeof SessionTenantAdminPaymentsRoute
  '/explore/apps': typeof SessionTenantExploreAppsRoute
  '/outputs/$outputId': typeof SessionTenantOutputsOutputIdRoute
  '/team/new': typeof SessionTenantTeamNewRoute
  '/work/admission': typeof SessionTenantWorkAdmissionRoute
  '/work/agents': typeof SessionTenantWorkAgentsRoute
  '/work/approvals': typeof SessionTenantWorkApprovalsRoute
  '/work/attempts': typeof SessionTenantWorkAttemptsRoute
  '/work/capacity': typeof SessionTenantWorkCapacityRoute
  '/work/cases': typeof SessionTenantWorkCasesRouteWithChildren
  '/work/clusters': typeof SessionTenantWorkClustersRoute
  '/work/control': typeof SessionTenantWorkControlRoute
  '/work/graph': typeof SessionTenantWorkGraphRoute
  '/work/interactions': typeof SessionTenantWorkInteractionsRouteWithChildren
  '/work/office': typeof SessionTenantWorkOfficeRoute
  '/work/portfolio': typeof SessionTenantWorkPortfolioRoute
  '/work/queue': typeof SessionTenantWorkQueueRoute
  '/work/recovery': typeof SessionTenantWorkRecoveryRoute
  '/admin': typeof SessionTenantAdminIndexRoute
  '/skills': typeof SessionTenantSkillsIndexRoute
  '/work': typeof SessionTenantWorkIndexRoute
  '/apps/$appId/analytics': typeof SessionTenantAppsAppIdAnalyticsRoute
  '/apps/$appId/content': typeof SessionTenantAppsAppIdContentRoute
  '/apps/$appId/settings': typeof SessionTenantAppsAppIdSettingsRoute
  '/apps/$appId/tools': typeof SessionTenantAppsAppIdToolsRoute
  '/explore/apps/$slug': typeof SessionTenantExploreAppsSlugRoute
  '/skills/$skillId/runs': typeof SessionTenantSkillsSkillIdRunsRoute
  '/skills/$skillId/schedule': typeof SessionTenantSkillsSkillIdScheduleRoute
  '/skills/$skillId/versions': typeof SessionTenantSkillsSkillIdVersionsRoute
  '/team/$tediId/authority': typeof SessionTenantTeamTediIdAuthorityRoute
  '/team/$tediId/learning': typeof SessionTenantTeamTediIdLearningRoute
  '/team/$tediId/memory': typeof SessionTenantTeamTediIdMemoryRoute
  '/team/$tediId/settings': typeof SessionTenantTeamTediIdSettingsRoute
  '/team/$tediId/telemetry': typeof SessionTenantTeamTediIdTelemetryRoute
  '/work/cases/$caseId': typeof SessionTenantWorkCasesCaseIdRoute
  '/work/executions/$runId': typeof SessionTenantWorkExecutionsRunIdRoute
  '/work/interactions/$requestId': typeof SessionTenantWorkInteractionsRequestIdRoute
  '/work/items/$workItemId': typeof SessionTenantWorkItemsWorkItemIdRoute
  '/work/projects/$projectId': typeof SessionTenantWorkProjectsProjectIdRoute
  '/work/runs/$runId': typeof SessionTenantWorkRunsRunIdRoute
  '/apps/$appId': typeof SessionTenantAppsAppIdIndexRoute
  '/skills/$skillId': typeof SessionTenantSkillsSkillIdIndexRoute
  '/team/$tediId': typeof SessionTenantTeamTediIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_cli-session': typeof CliSessionRouteWithChildren
  '/_session': typeof SessionRouteWithChildren
  '/_auth/invite': typeof AuthInviteRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_session/_chrome-free': typeof SessionChromeFreeRouteWithChildren
  '/_session/_tenant': typeof SessionTenantRouteWithChildren
  '/_session/account': typeof SessionAccountRouteWithChildren
  '/_auth/oauth/consent': typeof AuthOauthConsentRoute
  '/_cli-session/cli/login': typeof CliSessionCliLoginRoute
  '/_session/_chrome-free/shared': typeof SessionChromeFreeSharedRoute
  '/_session/_tenant/admin': typeof SessionTenantAdminRouteWithChildren
  '/_session/_tenant/apps': typeof SessionTenantAppsRoute
  '/_session/_tenant/audit': typeof SessionTenantAuditRoute
  '/_session/_tenant/blueprints': typeof SessionTenantBlueprintsRoute
  '/_session/_tenant/brain': typeof SessionTenantBrainRoute
  '/_session/_tenant/chat': typeof SessionTenantChatRoute
  '/_session/_tenant/compute': typeof SessionTenantComputeRoute
  '/_session/_tenant/gateways': typeof SessionTenantGatewaysRoute
  '/_session/_tenant/install': typeof SessionTenantInstallRoute
  '/_session/_tenant/outputs': typeof SessionTenantOutputsRoute
  '/_session/_tenant/sites': typeof SessionTenantSitesRoute
  '/_session/_tenant/skills': typeof SessionTenantSkillsRouteWithChildren
  '/_session/_tenant/team': typeof SessionTenantTeamRoute
  '/_session/_tenant/widget': typeof SessionTenantWidgetRoute
  '/_session/_tenant/work': typeof SessionTenantWorkRouteWithChildren
  '/_session/_tenant/workspaces': typeof SessionTenantWorkspacesRoute
  '/_session/account/authorizations': typeof SessionAccountAuthorizationsRoute
  '/_session/account/onboarding': typeof SessionAccountOnboardingRoute
  '/_session/account/organizations': typeof SessionAccountOrganizationsRoute
  '/_session/account/profile': typeof SessionAccountProfileRoute
  '/_session/_tenant/': typeof SessionTenantIndexRoute
  '/_session/_chrome-free/oauth/callback': typeof SessionChromeFreeOauthCallbackRoute
  '/_session/_chrome-free/workspace_/$workspaceId': typeof SessionChromeFreeWorkspaceWorkspaceIdRoute
  '/_session/_tenant/account/connections': typeof SessionTenantAccountConnectionsRoute
  '/_session/_tenant/account/settings': typeof SessionTenantAccountSettingsRoute
  '/_session/_tenant/admin/api-keys': typeof SessionTenantAdminApiKeysRoute
  '/_session/_tenant/admin/billing': typeof SessionTenantAdminBillingRoute
  '/_session/_tenant/admin/connections': typeof SessionTenantAdminConnectionsRoute
  '/_session/_tenant/admin/organization': typeof SessionTenantAdminOrganizationRoute
  '/_session/_tenant/admin/payments': typeof SessionTenantAdminPaymentsRoute
  '/_session/_tenant/apps_/$appId': typeof SessionTenantAppsAppIdRouteWithChildren
  '/_session/_tenant/explore/apps': typeof SessionTenantExploreAppsRoute
  '/_session/_tenant/outputs_/$outputId': typeof SessionTenantOutputsOutputIdRoute
  '/_session/_tenant/skills/$skillId': typeof SessionTenantSkillsSkillIdRouteWithChildren
  '/_session/_tenant/team_/$tediId': typeof SessionTenantTeamTediIdRouteWithChildren
  '/_session/_tenant/team_/new': typeof SessionTenantTeamNewRoute
  '/_session/_tenant/work/admission': typeof SessionTenantWorkAdmissionRoute
  '/_session/_tenant/work/agents': typeof SessionTenantWorkAgentsRoute
  '/_session/_tenant/work/approvals': typeof SessionTenantWorkApprovalsRoute
  '/_session/_tenant/work/attempts': typeof SessionTenantWorkAttemptsRoute
  '/_session/_tenant/work/capacity': typeof SessionTenantWorkCapacityRoute
  '/_session/_tenant/work/cases': typeof SessionTenantWorkCasesRouteWithChildren
  '/_session/_tenant/work/clusters': typeof SessionTenantWorkClustersRoute
  '/_session/_tenant/work/control': typeof SessionTenantWorkControlRoute
  '/_session/_tenant/work/graph': typeof SessionTenantWorkGraphRoute
  '/_session/_tenant/work/interactions': typeof SessionTenantWorkInteractionsRouteWithChildren
  '/_session/_tenant/work/office': typeof SessionTenantWorkOfficeRoute
  '/_session/_tenant/work/portfolio': typeof SessionTenantWorkPortfolioRoute
  '/_session/_tenant/work/queue': typeof SessionTenantWorkQueueRoute
  '/_session/_tenant/work/recovery': typeof SessionTenantWorkRecoveryRoute
  '/_session/_tenant/admin/': typeof SessionTenantAdminIndexRoute
  '/_session/_tenant/skills/': typeof SessionTenantSkillsIndexRoute
  '/_session/_tenant/work/': typeof SessionTenantWorkIndexRoute
  '/_session/_tenant/apps_/$appId/analytics': typeof SessionTenantAppsAppIdAnalyticsRoute
  '/_session/_tenant/apps_/$appId/content': typeof SessionTenantAppsAppIdContentRoute
  '/_session/_tenant/apps_/$appId/settings': typeof SessionTenantAppsAppIdSettingsRoute
  '/_session/_tenant/apps_/$appId/tools': typeof SessionTenantAppsAppIdToolsRoute
  '/_session/_tenant/explore/apps_/$slug': typeof SessionTenantExploreAppsSlugRoute
  '/_session/_tenant/skills/$skillId/runs': typeof SessionTenantSkillsSkillIdRunsRoute
  '/_session/_tenant/skills/$skillId/schedule': typeof SessionTenantSkillsSkillIdScheduleRoute
  '/_session/_tenant/skills/$skillId/versions': typeof SessionTenantSkillsSkillIdVersionsRoute
  '/_session/_tenant/team_/$tediId/authority': typeof SessionTenantTeamTediIdAuthorityRoute
  '/_session/_tenant/team_/$tediId/learning': typeof SessionTenantTeamTediIdLearningRoute
  '/_session/_tenant/team_/$tediId/memory': typeof SessionTenantTeamTediIdMemoryRoute
  '/_session/_tenant/team_/$tediId/settings': typeof SessionTenantTeamTediIdSettingsRoute
  '/_session/_tenant/team_/$tediId/telemetry': typeof SessionTenantTeamTediIdTelemetryRoute
  '/_session/_tenant/work/cases/$caseId': typeof SessionTenantWorkCasesCaseIdRoute
  '/_session/_tenant/work/executions/$runId': typeof SessionTenantWorkExecutionsRunIdRoute
  '/_session/_tenant/work/interactions/$requestId': typeof SessionTenantWorkInteractionsRequestIdRoute
  '/_session/_tenant/work/items/$workItemId': typeof SessionTenantWorkItemsWorkItemIdRoute
  '/_session/_tenant/work/projects/$projectId': typeof SessionTenantWorkProjectsProjectIdRoute
  '/_session/_tenant/work/runs/$runId': typeof SessionTenantWorkRunsRunIdRoute
  '/_session/_tenant/apps_/$appId/': typeof SessionTenantAppsAppIdIndexRoute
  '/_session/_tenant/skills/$skillId/': typeof SessionTenantSkillsSkillIdIndexRoute
  '/_session/_tenant/team_/$tediId/': typeof SessionTenantTeamTediIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/login'
    | '/account'
    | '/oauth/consent'
    | '/cli/login'
    | '/shared'
    | '/admin'
    | '/apps'
    | '/audit'
    | '/blueprints'
    | '/brain'
    | '/chat'
    | '/compute'
    | '/gateways'
    | '/install'
    | '/outputs'
    | '/sites'
    | '/skills'
    | '/team'
    | '/widget'
    | '/work'
    | '/workspaces'
    | '/account/authorizations'
    | '/account/onboarding'
    | '/account/organizations'
    | '/account/profile'
    | '/oauth/callback'
    | '/workspace/$workspaceId'
    | '/account/connections'
    | '/account/settings'
    | '/admin/api-keys'
    | '/admin/billing'
    | '/admin/connections'
    | '/admin/organization'
    | '/admin/payments'
    | '/apps/$appId'
    | '/explore/apps'
    | '/outputs/$outputId'
    | '/skills/$skillId'
    | '/team/$tediId'
    | '/team/new'
    | '/work/admission'
    | '/work/agents'
    | '/work/approvals'
    | '/work/attempts'
    | '/work/capacity'
    | '/work/cases'
    | '/work/clusters'
    | '/work/control'
    | '/work/graph'
    | '/work/interactions'
    | '/work/office'
    | '/work/portfolio'
    | '/work/queue'
    | '/work/recovery'
    | '/admin/'
    | '/skills/'
    | '/work/'
    | '/apps/$appId/analytics'
    | '/apps/$appId/content'
    | '/apps/$appId/settings'
    | '/apps/$appId/tools'
    | '/explore/apps/$slug'
    | '/skills/$skillId/runs'
    | '/skills/$skillId/schedule'
    | '/skills/$skillId/versions'
    | '/team/$tediId/authority'
    | '/team/$tediId/learning'
    | '/team/$tediId/memory'
    | '/team/$tediId/settings'
    | '/team/$tediId/telemetry'
    | '/work/cases/$caseId'
    | '/work/executions/$runId'
    | '/work/interactions/$requestId'
    | '/work/items/$workItemId'
    | '/work/projects/$projectId'
    | '/work/runs/$runId'
    | '/apps/$appId/'
    | '/skills/$skillId/'
    | '/team/$tediId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite'
    | '/login'
    | '/account'
    | '/oauth/consent'
    | '/cli/login'
    | '/shared'
    | '/apps'
    | '/audit'
    | '/blueprints'
    | '/brain'
    | '/chat'
    | '/compute'
    | '/gateways'
    | '/install'
    | '/outputs'
    | '/sites'
    | '/team'
    | '/widget'
    | '/workspaces'
    | '/account/authorizations'
    | '/account/onboarding'
    | '/account/organizations'
    | '/account/profile'
    | '/oauth/callback'
    | '/workspace/$workspaceId'
    | '/account/connections'
    | '/account/settings'
    | '/admin/api-keys'
    | '/admin/billing'
    | '/admin/connections'
    | '/admin/organization'
    | '/admin/payments'
    | '/explore/apps'
    | '/outputs/$outputId'
    | '/team/new'
    | '/work/admission'
    | '/work/agents'
    | '/work/approvals'
    | '/work/attempts'
    | '/work/capacity'
    | '/work/cases'
    | '/work/clusters'
    | '/work/control'
    | '/work/graph'
    | '/work/interactions'
    | '/work/office'
    | '/work/portfolio'
    | '/work/queue'
    | '/work/recovery'
    | '/admin'
    | '/skills'
    | '/work'
    | '/apps/$appId/analytics'
    | '/apps/$appId/content'
    | '/apps/$appId/settings'
    | '/apps/$appId/tools'
    | '/explore/apps/$slug'
    | '/skills/$skillId/runs'
    | '/skills/$skillId/schedule'
    | '/skills/$skillId/versions'
    | '/team/$tediId/authority'
    | '/team/$tediId/learning'
    | '/team/$tediId/memory'
    | '/team/$tediId/settings'
    | '/team/$tediId/telemetry'
    | '/work/cases/$caseId'
    | '/work/executions/$runId'
    | '/work/interactions/$requestId'
    | '/work/items/$workItemId'
    | '/work/projects/$projectId'
    | '/work/runs/$runId'
    | '/apps/$appId'
    | '/skills/$skillId'
    | '/team/$tediId'
  id:
    | '__root__'
    | '/_auth'
    | '/_cli-session'
    | '/_session'
    | '/_auth/invite'
    | '/_auth/login'
    | '/_session/_chrome-free'
    | '/_session/_tenant'
    | '/_session/account'
    | '/_auth/oauth/consent'
    | '/_cli-session/cli/login'
    | '/_session/_chrome-free/shared'
    | '/_session/_tenant/admin'
    | '/_session/_tenant/apps'
    | '/_session/_tenant/audit'
    | '/_session/_tenant/blueprints'
    | '/_session/_tenant/brain'
    | '/_session/_tenant/chat'
    | '/_session/_tenant/compute'
    | '/_session/_tenant/gateways'
    | '/_session/_tenant/install'
    | '/_session/_tenant/outputs'
    | '/_session/_tenant/sites'
    | '/_session/_tenant/skills'
    | '/_session/_tenant/team'
    | '/_session/_tenant/widget'
    | '/_session/_tenant/work'
    | '/_session/_tenant/workspaces'
    | '/_session/account/authorizations'
    | '/_session/account/onboarding'
    | '/_session/account/organizations'
    | '/_session/account/profile'
    | '/_session/_tenant/'
    | '/_session/_chrome-free/oauth/callback'
    | '/_session/_chrome-free/workspace_/$workspaceId'
    | '/_session/_tenant/account/connections'
    | '/_session/_tenant/account/settings'
    | '/_session/_tenant/admin/api-keys'
    | '/_session/_tenant/admin/billing'
    | '/_session/_tenant/admin/connections'
    | '/_session/_tenant/admin/organization'
    | '/_session/_tenant/admin/payments'
    | '/_session/_tenant/apps_/$appId'
    | '/_session/_tenant/explore/apps'
    | '/_session/_tenant/outputs_/$outputId'
    | '/_session/_tenant/skills/$skillId'
    | '/_session/_tenant/team_/$tediId'
    | '/_session/_tenant/team_/new'
    | '/_session/_tenant/work/admission'
    | '/_session/_tenant/work/agents'
    | '/_session/_tenant/work/approvals'
    | '/_session/_tenant/work/attempts'
    | '/_session/_tenant/work/capacity'
    | '/_session/_tenant/work/cases'
    | '/_session/_tenant/work/clusters'
    | '/_session/_tenant/work/control'
    | '/_session/_tenant/work/graph'
    | '/_session/_tenant/work/interactions'
    | '/_session/_tenant/work/office'
    | '/_session/_tenant/work/portfolio'
    | '/_session/_tenant/work/queue'
    | '/_session/_tenant/work/recovery'
    | '/_session/_tenant/admin/'
    | '/_session/_tenant/skills/'
    | '/_session/_tenant/work/'
    | '/_session/_tenant/apps_/$appId/analytics'
    | '/_session/_tenant/apps_/$appId/content'
    | '/_session/_tenant/apps_/$appId/settings'
    | '/_session/_tenant/apps_/$appId/tools'
    | '/_session/_tenant/explore/apps_/$slug'
    | '/_session/_tenant/skills/$skillId/runs'
    | '/_session/_tenant/skills/$skillId/schedule'
    | '/_session/_tenant/skills/$skillId/versions'
    | '/_session/_tenant/team_/$tediId/authority'
    | '/_session/_tenant/team_/$tediId/learning'
    | '/_session/_tenant/team_/$tediId/memory'
    | '/_session/_tenant/team_/$tediId/settings'
    | '/_session/_tenant/team_/$tediId/telemetry'
    | '/_session/_tenant/work/cases/$caseId'
    | '/_session/_tenant/work/executions/$runId'
    | '/_session/_tenant/work/interactions/$requestId'
    | '/_session/_tenant/work/items/$workItemId'
    | '/_session/_tenant/work/projects/$projectId'
    | '/_session/_tenant/work/runs/$runId'
    | '/_session/_tenant/apps_/$appId/'
    | '/_session/_tenant/skills/$skillId/'
    | '/_session/_tenant/team_/$tediId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  CliSessionRoute: typeof CliSessionRouteWithChildren
  SessionRoute: typeof SessionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_cli-session': {
      id: '/_cli-session'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CliSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_session': {
      id: '/_session'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/invite': {
      id: '/_auth/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_session/_chrome-free': {
      id: '/_session/_chrome-free'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SessionChromeFreeRouteImport
      parentRoute: typeof SessionRoute
    }
    '/_session/_tenant': {
      id: '/_session/_tenant'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SessionTenantRouteImport
      parentRoute: typeof SessionRoute
    }
    '/_session/account': {
      id: '/_session/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof SessionAccountRouteImport
      parentRoute: typeof SessionRoute
    }
    '/_auth/oauth/consent': {
      id: '/_auth/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof AuthOauthConsentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_cli-session/cli/login': {
      id: '/_cli-session/cli/login'
      path: '/cli/login'
      fullPath: '/cli/login'
      preLoaderRoute: typeof CliSessionCliLoginRouteImport
      parentRoute: typeof CliSessionRoute
    }
    '/_session/_chrome-free/shared': {
      id: '/_session/_chrome-free/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SessionChromeFreeSharedRouteImport
      parentRoute: typeof SessionChromeFreeRoute
    }
    '/_session/_tenant/': {
      id: '/_session/_tenant/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SessionTenantIndexRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/admin': {
      id: '/_session/_tenant/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof SessionTenantAdminRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/apps': {
      id: '/_session/_tenant/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof SessionTenantAppsRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/audit': {
      id: '/_session/_tenant/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof SessionTenantAuditRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/blueprints': {
      id: '/_session/_tenant/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof SessionTenantBlueprintsRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/brain': {
      id: '/_session/_tenant/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof SessionTenantBrainRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/chat': {
      id: '/_session/_tenant/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof SessionTenantChatRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/compute': {
      id: '/_session/_tenant/compute'
      path: '/compute'
      fullPath: '/compute'
      preLoaderRoute: typeof SessionTenantComputeRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/gateways': {
      id: '/_session/_tenant/gateways'
      path: '/gateways'
      fullPath: '/gateways'
      preLoaderRoute: typeof SessionTenantGatewaysRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/install': {
      id: '/_session/_tenant/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof SessionTenantInstallRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/outputs': {
      id: '/_session/_tenant/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof SessionTenantOutputsRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/sites': {
      id: '/_session/_tenant/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SessionTenantSitesRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/skills': {
      id: '/_session/_tenant/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SessionTenantSkillsRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/team': {
      id: '/_session/_tenant/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof SessionTenantTeamRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/widget': {
      id: '/_session/_tenant/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof SessionTenantWidgetRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/work': {
      id: '/_session/_tenant/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof SessionTenantWorkRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/workspaces': {
      id: '/_session/_tenant/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof SessionTenantWorkspacesRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/account/authorizations': {
      id: '/_session/account/authorizations'
      path: '/authorizations'
      fullPath: '/account/authorizations'
      preLoaderRoute: typeof SessionAccountAuthorizationsRouteImport
      parentRoute: typeof SessionAccountRoute
    }
    '/_session/account/onboarding': {
      id: '/_session/account/onboarding'
      path: '/onboarding'
      fullPath: '/account/onboarding'
      preLoaderRoute: typeof SessionAccountOnboardingRouteImport
      parentRoute: typeof SessionAccountRoute
    }
    '/_session/account/organizations': {
      id: '/_session/account/organizations'
      path: '/organizations'
      fullPath: '/account/organizations'
      preLoaderRoute: typeof SessionAccountOrganizationsRouteImport
      parentRoute: typeof SessionAccountRoute
    }
    '/_session/account/profile': {
      id: '/_session/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof SessionAccountProfileRouteImport
      parentRoute: typeof SessionAccountRoute
    }
    '/_session/_chrome-free/oauth/callback': {
      id: '/_session/_chrome-free/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof SessionChromeFreeOauthCallbackRouteImport
      parentRoute: typeof SessionChromeFreeRoute
    }
    '/_session/_chrome-free/workspace_/$workspaceId': {
      id: '/_session/_chrome-free/workspace_/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof SessionChromeFreeWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof SessionChromeFreeRoute
    }
    '/_session/_tenant/account/connections': {
      id: '/_session/_tenant/account/connections'
      path: '/account/connections'
      fullPath: '/account/connections'
      preLoaderRoute: typeof SessionTenantAccountConnectionsRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/account/settings': {
      id: '/_session/_tenant/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof SessionTenantAccountSettingsRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/admin/': {
      id: '/_session/_tenant/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof SessionTenantAdminIndexRouteImport
      parentRoute: typeof SessionTenantAdminRoute
    }
    '/_session/_tenant/admin/api-keys': {
      id: '/_session/_tenant/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof SessionTenantAdminApiKeysRouteImport
      parentRoute: typeof SessionTenantAdminRoute
    }
    '/_session/_tenant/admin/billing': {
      id: '/_session/_tenant/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof SessionTenantAdminBillingRouteImport
      parentRoute: typeof SessionTenantAdminRoute
    }
    '/_session/_tenant/admin/connections': {
      id: '/_session/_tenant/admin/connections'
      path: '/connections'
      fullPath: '/admin/connections'
      preLoaderRoute: typeof SessionTenantAdminConnectionsRouteImport
      parentRoute: typeof SessionTenantAdminRoute
    }
    '/_session/_tenant/admin/organization': {
      id: '/_session/_tenant/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof SessionTenantAdminOrganizationRouteImport
      parentRoute: typeof SessionTenantAdminRoute
    }
    '/_session/_tenant/admin/payments': {
      id: '/_session/_tenant/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof SessionTenantAdminPaymentsRouteImport
      parentRoute: typeof SessionTenantAdminRoute
    }
    '/_session/_tenant/apps_/$appId': {
      id: '/_session/_tenant/apps_/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof SessionTenantAppsAppIdRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/explore/apps': {
      id: '/_session/_tenant/explore/apps'
      path: '/explore/apps'
      fullPath: '/explore/apps'
      preLoaderRoute: typeof SessionTenantExploreAppsRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/outputs_/$outputId': {
      id: '/_session/_tenant/outputs_/$outputId'
      path: '/outputs/$outputId'
      fullPath: '/outputs/$outputId'
      preLoaderRoute: typeof SessionTenantOutputsOutputIdRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/skills/': {
      id: '/_session/_tenant/skills/'
      path: '/'
      fullPath: '/skills/'
      preLoaderRoute: typeof SessionTenantSkillsIndexRouteImport
      parentRoute: typeof SessionTenantSkillsRoute
    }
    '/_session/_tenant/skills/$skillId': {
      id: '/_session/_tenant/skills/$skillId'
      path: '/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof SessionTenantSkillsSkillIdRouteImport
      parentRoute: typeof SessionTenantSkillsRoute
    }
    '/_session/_tenant/team_/$tediId': {
      id: '/_session/_tenant/team_/$tediId'
      path: '/team/$tediId'
      fullPath: '/team/$tediId'
      preLoaderRoute: typeof SessionTenantTeamTediIdRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/team_/new': {
      id: '/_session/_tenant/team_/new'
      path: '/team/new'
      fullPath: '/team/new'
      preLoaderRoute: typeof SessionTenantTeamNewRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/work/': {
      id: '/_session/_tenant/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof SessionTenantWorkIndexRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/admission': {
      id: '/_session/_tenant/work/admission'
      path: '/admission'
      fullPath: '/work/admission'
      preLoaderRoute: typeof SessionTenantWorkAdmissionRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/agents': {
      id: '/_session/_tenant/work/agents'
      path: '/agents'
      fullPath: '/work/agents'
      preLoaderRoute: typeof SessionTenantWorkAgentsRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/approvals': {
      id: '/_session/_tenant/work/approvals'
      path: '/approvals'
      fullPath: '/work/approvals'
      preLoaderRoute: typeof SessionTenantWorkApprovalsRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/attempts': {
      id: '/_session/_tenant/work/attempts'
      path: '/attempts'
      fullPath: '/work/attempts'
      preLoaderRoute: typeof SessionTenantWorkAttemptsRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/capacity': {
      id: '/_session/_tenant/work/capacity'
      path: '/capacity'
      fullPath: '/work/capacity'
      preLoaderRoute: typeof SessionTenantWorkCapacityRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/cases': {
      id: '/_session/_tenant/work/cases'
      path: '/cases'
      fullPath: '/work/cases'
      preLoaderRoute: typeof SessionTenantWorkCasesRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/clusters': {
      id: '/_session/_tenant/work/clusters'
      path: '/clusters'
      fullPath: '/work/clusters'
      preLoaderRoute: typeof SessionTenantWorkClustersRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/control': {
      id: '/_session/_tenant/work/control'
      path: '/control'
      fullPath: '/work/control'
      preLoaderRoute: typeof SessionTenantWorkControlRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/graph': {
      id: '/_session/_tenant/work/graph'
      path: '/graph'
      fullPath: '/work/graph'
      preLoaderRoute: typeof SessionTenantWorkGraphRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/interactions': {
      id: '/_session/_tenant/work/interactions'
      path: '/interactions'
      fullPath: '/work/interactions'
      preLoaderRoute: typeof SessionTenantWorkInteractionsRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/office': {
      id: '/_session/_tenant/work/office'
      path: '/office'
      fullPath: '/work/office'
      preLoaderRoute: typeof SessionTenantWorkOfficeRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/portfolio': {
      id: '/_session/_tenant/work/portfolio'
      path: '/portfolio'
      fullPath: '/work/portfolio'
      preLoaderRoute: typeof SessionTenantWorkPortfolioRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/queue': {
      id: '/_session/_tenant/work/queue'
      path: '/queue'
      fullPath: '/work/queue'
      preLoaderRoute: typeof SessionTenantWorkQueueRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/recovery': {
      id: '/_session/_tenant/work/recovery'
      path: '/recovery'
      fullPath: '/work/recovery'
      preLoaderRoute: typeof SessionTenantWorkRecoveryRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/apps_/$appId/': {
      id: '/_session/_tenant/apps_/$appId/'
      path: '/'
      fullPath: '/apps/$appId/'
      preLoaderRoute: typeof SessionTenantAppsAppIdIndexRouteImport
      parentRoute: typeof SessionTenantAppsAppIdRoute
    }
    '/_session/_tenant/apps_/$appId/analytics': {
      id: '/_session/_tenant/apps_/$appId/analytics'
      path: '/analytics'
      fullPath: '/apps/$appId/analytics'
      preLoaderRoute: typeof SessionTenantAppsAppIdAnalyticsRouteImport
      parentRoute: typeof SessionTenantAppsAppIdRoute
    }
    '/_session/_tenant/apps_/$appId/content': {
      id: '/_session/_tenant/apps_/$appId/content'
      path: '/content'
      fullPath: '/apps/$appId/content'
      preLoaderRoute: typeof SessionTenantAppsAppIdContentRouteImport
      parentRoute: typeof SessionTenantAppsAppIdRoute
    }
    '/_session/_tenant/apps_/$appId/settings': {
      id: '/_session/_tenant/apps_/$appId/settings'
      path: '/settings'
      fullPath: '/apps/$appId/settings'
      preLoaderRoute: typeof SessionTenantAppsAppIdSettingsRouteImport
      parentRoute: typeof SessionTenantAppsAppIdRoute
    }
    '/_session/_tenant/apps_/$appId/tools': {
      id: '/_session/_tenant/apps_/$appId/tools'
      path: '/tools'
      fullPath: '/apps/$appId/tools'
      preLoaderRoute: typeof SessionTenantAppsAppIdToolsRouteImport
      parentRoute: typeof SessionTenantAppsAppIdRoute
    }
    '/_session/_tenant/explore/apps_/$slug': {
      id: '/_session/_tenant/explore/apps_/$slug'
      path: '/explore/apps/$slug'
      fullPath: '/explore/apps/$slug'
      preLoaderRoute: typeof SessionTenantExploreAppsSlugRouteImport
      parentRoute: typeof SessionTenantRoute
    }
    '/_session/_tenant/skills/$skillId/': {
      id: '/_session/_tenant/skills/$skillId/'
      path: '/'
      fullPath: '/skills/$skillId/'
      preLoaderRoute: typeof SessionTenantSkillsSkillIdIndexRouteImport
      parentRoute: typeof SessionTenantSkillsSkillIdRoute
    }
    '/_session/_tenant/skills/$skillId/runs': {
      id: '/_session/_tenant/skills/$skillId/runs'
      path: '/runs'
      fullPath: '/skills/$skillId/runs'
      preLoaderRoute: typeof SessionTenantSkillsSkillIdRunsRouteImport
      parentRoute: typeof SessionTenantSkillsSkillIdRoute
    }
    '/_session/_tenant/skills/$skillId/schedule': {
      id: '/_session/_tenant/skills/$skillId/schedule'
      path: '/schedule'
      fullPath: '/skills/$skillId/schedule'
      preLoaderRoute: typeof SessionTenantSkillsSkillIdScheduleRouteImport
      parentRoute: typeof SessionTenantSkillsSkillIdRoute
    }
    '/_session/_tenant/skills/$skillId/versions': {
      id: '/_session/_tenant/skills/$skillId/versions'
      path: '/versions'
      fullPath: '/skills/$skillId/versions'
      preLoaderRoute: typeof SessionTenantSkillsSkillIdVersionsRouteImport
      parentRoute: typeof SessionTenantSkillsSkillIdRoute
    }
    '/_session/_tenant/team_/$tediId/': {
      id: '/_session/_tenant/team_/$tediId/'
      path: '/'
      fullPath: '/team/$tediId/'
      preLoaderRoute: typeof SessionTenantTeamTediIdIndexRouteImport
      parentRoute: typeof SessionTenantTeamTediIdRoute
    }
    '/_session/_tenant/team_/$tediId/authority': {
      id: '/_session/_tenant/team_/$tediId/authority'
      path: '/authority'
      fullPath: '/team/$tediId/authority'
      preLoaderRoute: typeof SessionTenantTeamTediIdAuthorityRouteImport
      parentRoute: typeof SessionTenantTeamTediIdRoute
    }
    '/_session/_tenant/team_/$tediId/learning': {
      id: '/_session/_tenant/team_/$tediId/learning'
      path: '/learning'
      fullPath: '/team/$tediId/learning'
      preLoaderRoute: typeof SessionTenantTeamTediIdLearningRouteImport
      parentRoute: typeof SessionTenantTeamTediIdRoute
    }
    '/_session/_tenant/team_/$tediId/memory': {
      id: '/_session/_tenant/team_/$tediId/memory'
      path: '/memory'
      fullPath: '/team/$tediId/memory'
      preLoaderRoute: typeof SessionTenantTeamTediIdMemoryRouteImport
      parentRoute: typeof SessionTenantTeamTediIdRoute
    }
    '/_session/_tenant/team_/$tediId/settings': {
      id: '/_session/_tenant/team_/$tediId/settings'
      path: '/settings'
      fullPath: '/team/$tediId/settings'
      preLoaderRoute: typeof SessionTenantTeamTediIdSettingsRouteImport
      parentRoute: typeof SessionTenantTeamTediIdRoute
    }
    '/_session/_tenant/team_/$tediId/telemetry': {
      id: '/_session/_tenant/team_/$tediId/telemetry'
      path: '/telemetry'
      fullPath: '/team/$tediId/telemetry'
      preLoaderRoute: typeof SessionTenantTeamTediIdTelemetryRouteImport
      parentRoute: typeof SessionTenantTeamTediIdRoute
    }
    '/_session/_tenant/work/cases/$caseId': {
      id: '/_session/_tenant/work/cases/$caseId'
      path: '/$caseId'
      fullPath: '/work/cases/$caseId'
      preLoaderRoute: typeof SessionTenantWorkCasesCaseIdRouteImport
      parentRoute: typeof SessionTenantWorkCasesRoute
    }
    '/_session/_tenant/work/executions/$runId': {
      id: '/_session/_tenant/work/executions/$runId'
      path: '/executions/$runId'
      fullPath: '/work/executions/$runId'
      preLoaderRoute: typeof SessionTenantWorkExecutionsRunIdRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/interactions/$requestId': {
      id: '/_session/_tenant/work/interactions/$requestId'
      path: '/$requestId'
      fullPath: '/work/interactions/$requestId'
      preLoaderRoute: typeof SessionTenantWorkInteractionsRequestIdRouteImport
      parentRoute: typeof SessionTenantWorkInteractionsRoute
    }
    '/_session/_tenant/work/items/$workItemId': {
      id: '/_session/_tenant/work/items/$workItemId'
      path: '/items/$workItemId'
      fullPath: '/work/items/$workItemId'
      preLoaderRoute: typeof SessionTenantWorkItemsWorkItemIdRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/projects/$projectId': {
      id: '/_session/_tenant/work/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/work/projects/$projectId'
      preLoaderRoute: typeof SessionTenantWorkProjectsProjectIdRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
    '/_session/_tenant/work/runs/$runId': {
      id: '/_session/_tenant/work/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/work/runs/$runId'
      preLoaderRoute: typeof SessionTenantWorkRunsRunIdRouteImport
      parentRoute: typeof SessionTenantWorkRoute
    }
  }
}

interface AuthRouteChildren {
  AuthInviteRoute: typeof AuthInviteRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOauthConsentRoute: typeof AuthOauthConsentRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthInviteRoute: AuthInviteRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOauthConsentRoute: AuthOauthConsentRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CliSessionRouteChildren {
  CliSessionCliLoginRoute: typeof CliSessionCliLoginRoute
}

const CliSessionRouteChildren: CliSessionRouteChildren = {
  CliSessionCliLoginRoute: CliSessionCliLoginRoute,
}

const CliSessionRouteWithChildren = CliSessionRoute._addFileChildren(
  CliSessionRouteChildren,
)

interface SessionChromeFreeRouteChildren {
  SessionChromeFreeSharedRoute: typeof SessionChromeFreeSharedRoute
  SessionChromeFreeOauthCallbackRoute: typeof SessionChromeFreeOauthCallbackRoute
  SessionChromeFreeWorkspaceWorkspaceIdRoute: typeof SessionChromeFreeWorkspaceWorkspaceIdRoute
}

const SessionChromeFreeRouteChildren: SessionChromeFreeRouteChildren = {
  SessionChromeFreeSharedRoute: SessionChromeFreeSharedRoute,
  SessionChromeFreeOauthCallbackRoute: SessionChromeFreeOauthCallbackRoute,
  SessionChromeFreeWorkspaceWorkspaceIdRoute:
    SessionChromeFreeWorkspaceWorkspaceIdRoute,
}

const SessionChromeFreeRouteWithChildren =
  SessionChromeFreeRoute._addFileChildren(SessionChromeFreeRouteChildren)

interface SessionTenantAdminRouteChildren {
  SessionTenantAdminApiKeysRoute: typeof SessionTenantAdminApiKeysRoute
  SessionTenantAdminBillingRoute: typeof SessionTenantAdminBillingRoute
  SessionTenantAdminConnectionsRoute: typeof SessionTenantAdminConnectionsRoute
  SessionTenantAdminOrganizationRoute: typeof SessionTenantAdminOrganizationRoute
  SessionTenantAdminPaymentsRoute: typeof SessionTenantAdminPaymentsRoute
  SessionTenantAdminIndexRoute: typeof SessionTenantAdminIndexRoute
}

const SessionTenantAdminRouteChildren: SessionTenantAdminRouteChildren = {
  SessionTenantAdminApiKeysRoute: SessionTenantAdminApiKeysRoute,
  SessionTenantAdminBillingRoute: SessionTenantAdminBillingRoute,
  SessionTenantAdminConnectionsRoute: SessionTenantAdminConnectionsRoute,
  SessionTenantAdminOrganizationRoute: SessionTenantAdminOrganizationRoute,
  SessionTenantAdminPaymentsRoute: SessionTenantAdminPaymentsRoute,
  SessionTenantAdminIndexRoute: SessionTenantAdminIndexRoute,
}

const SessionTenantAdminRouteWithChildren =
  SessionTenantAdminRoute._addFileChildren(SessionTenantAdminRouteChildren)

interface SessionTenantSkillsSkillIdRouteChildren {
  SessionTenantSkillsSkillIdRunsRoute: typeof SessionTenantSkillsSkillIdRunsRoute
  SessionTenantSkillsSkillIdScheduleRoute: typeof SessionTenantSkillsSkillIdScheduleRoute
  SessionTenantSkillsSkillIdVersionsRoute: typeof SessionTenantSkillsSkillIdVersionsRoute
  SessionTenantSkillsSkillIdIndexRoute: typeof SessionTenantSkillsSkillIdIndexRoute
}

const SessionTenantSkillsSkillIdRouteChildren: SessionTenantSkillsSkillIdRouteChildren =
  {
    SessionTenantSkillsSkillIdRunsRoute: SessionTenantSkillsSkillIdRunsRoute,
    SessionTenantSkillsSkillIdScheduleRoute:
      SessionTenantSkillsSkillIdScheduleRoute,
    SessionTenantSkillsSkillIdVersionsRoute:
      SessionTenantSkillsSkillIdVersionsRoute,
    SessionTenantSkillsSkillIdIndexRoute: SessionTenantSkillsSkillIdIndexRoute,
  }

const SessionTenantSkillsSkillIdRouteWithChildren =
  SessionTenantSkillsSkillIdRoute._addFileChildren(
    SessionTenantSkillsSkillIdRouteChildren,
  )

interface SessionTenantSkillsRouteChildren {
  SessionTenantSkillsSkillIdRoute: typeof SessionTenantSkillsSkillIdRouteWithChildren
  SessionTenantSkillsIndexRoute: typeof SessionTenantSkillsIndexRoute
}

const SessionTenantSkillsRouteChildren: SessionTenantSkillsRouteChildren = {
  SessionTenantSkillsSkillIdRoute: SessionTenantSkillsSkillIdRouteWithChildren,
  SessionTenantSkillsIndexRoute: SessionTenantSkillsIndexRoute,
}

const SessionTenantSkillsRouteWithChildren =
  SessionTenantSkillsRoute._addFileChildren(SessionTenantSkillsRouteChildren)

interface SessionTenantWorkCasesRouteChildren {
  SessionTenantWorkCasesCaseIdRoute: typeof SessionTenantWorkCasesCaseIdRoute
}

const SessionTenantWorkCasesRouteChildren: SessionTenantWorkCasesRouteChildren =
  {
    SessionTenantWorkCasesCaseIdRoute: SessionTenantWorkCasesCaseIdRoute,
  }

const SessionTenantWorkCasesRouteWithChildren =
  SessionTenantWorkCasesRoute._addFileChildren(
    SessionTenantWorkCasesRouteChildren,
  )

interface SessionTenantWorkInteractionsRouteChildren {
  SessionTenantWorkInteractionsRequestIdRoute: typeof SessionTenantWorkInteractionsRequestIdRoute
}

const SessionTenantWorkInteractionsRouteChildren: SessionTenantWorkInteractionsRouteChildren =
  {
    SessionTenantWorkInteractionsRequestIdRoute:
      SessionTenantWorkInteractionsRequestIdRoute,
  }

const SessionTenantWorkInteractionsRouteWithChildren =
  SessionTenantWorkInteractionsRoute._addFileChildren(
    SessionTenantWorkInteractionsRouteChildren,
  )

interface SessionTenantWorkRouteChildren {
  SessionTenantWorkAdmissionRoute: typeof SessionTenantWorkAdmissionRoute
  SessionTenantWorkAgentsRoute: typeof SessionTenantWorkAgentsRoute
  SessionTenantWorkApprovalsRoute: typeof SessionTenantWorkApprovalsRoute
  SessionTenantWorkAttemptsRoute: typeof SessionTenantWorkAttemptsRoute
  SessionTenantWorkCapacityRoute: typeof SessionTenantWorkCapacityRoute
  SessionTenantWorkCasesRoute: typeof SessionTenantWorkCasesRouteWithChildren
  SessionTenantWorkClustersRoute: typeof SessionTenantWorkClustersRoute
  SessionTenantWorkControlRoute: typeof SessionTenantWorkControlRoute
  SessionTenantWorkGraphRoute: typeof SessionTenantWorkGraphRoute
  SessionTenantWorkInteractionsRoute: typeof SessionTenantWorkInteractionsRouteWithChildren
  SessionTenantWorkOfficeRoute: typeof SessionTenantWorkOfficeRoute
  SessionTenantWorkPortfolioRoute: typeof SessionTenantWorkPortfolioRoute
  SessionTenantWorkQueueRoute: typeof SessionTenantWorkQueueRoute
  SessionTenantWorkRecoveryRoute: typeof SessionTenantWorkRecoveryRoute
  SessionTenantWorkIndexRoute: typeof SessionTenantWorkIndexRoute
  SessionTenantWorkExecutionsRunIdRoute: typeof SessionTenantWorkExecutionsRunIdRoute
  SessionTenantWorkItemsWorkItemIdRoute: typeof SessionTenantWorkItemsWorkItemIdRoute
  SessionTenantWorkProjectsProjectIdRoute: typeof SessionTenantWorkProjectsProjectIdRoute
  SessionTenantWorkRunsRunIdRoute: typeof SessionTenantWorkRunsRunIdRoute
}

const SessionTenantWorkRouteChildren: SessionTenantWorkRouteChildren = {
  SessionTenantWorkAdmissionRoute: SessionTenantWorkAdmissionRoute,
  SessionTenantWorkAgentsRoute: SessionTenantWorkAgentsRoute,
  SessionTenantWorkApprovalsRoute: SessionTenantWorkApprovalsRoute,
  SessionTenantWorkAttemptsRoute: SessionTenantWorkAttemptsRoute,
  SessionTenantWorkCapacityRoute: SessionTenantWorkCapacityRoute,
  SessionTenantWorkCasesRoute: SessionTenantWorkCasesRouteWithChildren,
  SessionTenantWorkClustersRoute: SessionTenantWorkClustersRoute,
  SessionTenantWorkControlRoute: SessionTenantWorkControlRoute,
  SessionTenantWorkGraphRoute: SessionTenantWorkGraphRoute,
  SessionTenantWorkInteractionsRoute:
    SessionTenantWorkInteractionsRouteWithChildren,
  SessionTenantWorkOfficeRoute: SessionTenantWorkOfficeRoute,
  SessionTenantWorkPortfolioRoute: SessionTenantWorkPortfolioRoute,
  SessionTenantWorkQueueRoute: SessionTenantWorkQueueRoute,
  SessionTenantWorkRecoveryRoute: SessionTenantWorkRecoveryRoute,
  SessionTenantWorkIndexRoute: SessionTenantWorkIndexRoute,
  SessionTenantWorkExecutionsRunIdRoute: SessionTenantWorkExecutionsRunIdRoute,
  SessionTenantWorkItemsWorkItemIdRoute: SessionTenantWorkItemsWorkItemIdRoute,
  SessionTenantWorkProjectsProjectIdRoute:
    SessionTenantWorkProjectsProjectIdRoute,
  SessionTenantWorkRunsRunIdRoute: SessionTenantWorkRunsRunIdRoute,
}

const SessionTenantWorkRouteWithChildren =
  SessionTenantWorkRoute._addFileChildren(SessionTenantWorkRouteChildren)

interface SessionTenantAppsAppIdRouteChildren {
  SessionTenantAppsAppIdAnalyticsRoute: typeof SessionTenantAppsAppIdAnalyticsRoute
  SessionTenantAppsAppIdContentRoute: typeof SessionTenantAppsAppIdContentRoute
  SessionTenantAppsAppIdSettingsRoute: typeof SessionTenantAppsAppIdSettingsRoute
  SessionTenantAppsAppIdToolsRoute: typeof SessionTenantAppsAppIdToolsRoute
  SessionTenantAppsAppIdIndexRoute: typeof SessionTenantAppsAppIdIndexRoute
}

const SessionTenantAppsAppIdRouteChildren: SessionTenantAppsAppIdRouteChildren =
  {
    SessionTenantAppsAppIdAnalyticsRoute: SessionTenantAppsAppIdAnalyticsRoute,
    SessionTenantAppsAppIdContentRoute: SessionTenantAppsAppIdContentRoute,
    SessionTenantAppsAppIdSettingsRoute: SessionTenantAppsAppIdSettingsRoute,
    SessionTenantAppsAppIdToolsRoute: SessionTenantAppsAppIdToolsRoute,
    SessionTenantAppsAppIdIndexRoute: SessionTenantAppsAppIdIndexRoute,
  }

const SessionTenantAppsAppIdRouteWithChildren =
  SessionTenantAppsAppIdRoute._addFileChildren(
    SessionTenantAppsAppIdRouteChildren,
  )

interface SessionTenantTeamTediIdRouteChildren {
  SessionTenantTeamTediIdAuthorityRoute: typeof SessionTenantTeamTediIdAuthorityRoute
  SessionTenantTeamTediIdLearningRoute: typeof SessionTenantTeamTediIdLearningRoute
  SessionTenantTeamTediIdMemoryRoute: typeof SessionTenantTeamTediIdMemoryRoute
  SessionTenantTeamTediIdSettingsRoute: typeof SessionTenantTeamTediIdSettingsRoute
  SessionTenantTeamTediIdTelemetryRoute: typeof SessionTenantTeamTediIdTelemetryRoute
  SessionTenantTeamTediIdIndexRoute: typeof SessionTenantTeamTediIdIndexRoute
}

const SessionTenantTeamTediIdRouteChildren: SessionTenantTeamTediIdRouteChildren =
  {
    SessionTenantTeamTediIdAuthorityRoute:
      SessionTenantTeamTediIdAuthorityRoute,
    SessionTenantTeamTediIdLearningRoute: SessionTenantTeamTediIdLearningRoute,
    SessionTenantTeamTediIdMemoryRoute: SessionTenantTeamTediIdMemoryRoute,
    SessionTenantTeamTediIdSettingsRoute: SessionTenantTeamTediIdSettingsRoute,
    SessionTenantTeamTediIdTelemetryRoute:
      SessionTenantTeamTediIdTelemetryRoute,
    SessionTenantTeamTediIdIndexRoute: SessionTenantTeamTediIdIndexRoute,
  }

const SessionTenantTeamTediIdRouteWithChildren =
  SessionTenantTeamTediIdRoute._addFileChildren(
    SessionTenantTeamTediIdRouteChildren,
  )

interface SessionTenantRouteChildren {
  SessionTenantAdminRoute: typeof SessionTenantAdminRouteWithChildren
  SessionTenantAppsRoute: typeof SessionTenantAppsRoute
  SessionTenantAuditRoute: typeof SessionTenantAuditRoute
  SessionTenantBlueprintsRoute: typeof SessionTenantBlueprintsRoute
  SessionTenantBrainRoute: typeof SessionTenantBrainRoute
  SessionTenantChatRoute: typeof SessionTenantChatRoute
  SessionTenantComputeRoute: typeof SessionTenantComputeRoute
  SessionTenantGatewaysRoute: typeof SessionTenantGatewaysRoute
  SessionTenantInstallRoute: typeof SessionTenantInstallRoute
  SessionTenantOutputsRoute: typeof SessionTenantOutputsRoute
  SessionTenantSitesRoute: typeof SessionTenantSitesRoute
  SessionTenantSkillsRoute: typeof SessionTenantSkillsRouteWithChildren
  SessionTenantTeamRoute: typeof SessionTenantTeamRoute
  SessionTenantWidgetRoute: typeof SessionTenantWidgetRoute
  SessionTenantWorkRoute: typeof SessionTenantWorkRouteWithChildren
  SessionTenantWorkspacesRoute: typeof SessionTenantWorkspacesRoute
  SessionTenantIndexRoute: typeof SessionTenantIndexRoute
  SessionTenantAccountConnectionsRoute: typeof SessionTenantAccountConnectionsRoute
  SessionTenantAccountSettingsRoute: typeof SessionTenantAccountSettingsRoute
  SessionTenantAppsAppIdRoute: typeof SessionTenantAppsAppIdRouteWithChildren
  SessionTenantExploreAppsRoute: typeof SessionTenantExploreAppsRoute
  SessionTenantOutputsOutputIdRoute: typeof SessionTenantOutputsOutputIdRoute
  SessionTenantTeamTediIdRoute: typeof SessionTenantTeamTediIdRouteWithChildren
  SessionTenantTeamNewRoute: typeof SessionTenantTeamNewRoute
  SessionTenantExploreAppsSlugRoute: typeof SessionTenantExploreAppsSlugRoute
}

const SessionTenantRouteChildren: SessionTenantRouteChildren = {
  SessionTenantAdminRoute: SessionTenantAdminRouteWithChildren,
  SessionTenantAppsRoute: SessionTenantAppsRoute,
  SessionTenantAuditRoute: SessionTenantAuditRoute,
  SessionTenantBlueprintsRoute: SessionTenantBlueprintsRoute,
  SessionTenantBrainRoute: SessionTenantBrainRoute,
  SessionTenantChatRoute: SessionTenantChatRoute,
  SessionTenantComputeRoute: SessionTenantComputeRoute,
  SessionTenantGatewaysRoute: SessionTenantGatewaysRoute,
  SessionTenantInstallRoute: SessionTenantInstallRoute,
  SessionTenantOutputsRoute: SessionTenantOutputsRoute,
  SessionTenantSitesRoute: SessionTenantSitesRoute,
  SessionTenantSkillsRoute: SessionTenantSkillsRouteWithChildren,
  SessionTenantTeamRoute: SessionTenantTeamRoute,
  SessionTenantWidgetRoute: SessionTenantWidgetRoute,
  SessionTenantWorkRoute: SessionTenantWorkRouteWithChildren,
  SessionTenantWorkspacesRoute: SessionTenantWorkspacesRoute,
  SessionTenantIndexRoute: SessionTenantIndexRoute,
  SessionTenantAccountConnectionsRoute: SessionTenantAccountConnectionsRoute,
  SessionTenantAccountSettingsRoute: SessionTenantAccountSettingsRoute,
  SessionTenantAppsAppIdRoute: SessionTenantAppsAppIdRouteWithChildren,
  SessionTenantExploreAppsRoute: SessionTenantExploreAppsRoute,
  SessionTenantOutputsOutputIdRoute: SessionTenantOutputsOutputIdRoute,
  SessionTenantTeamTediIdRoute: SessionTenantTeamTediIdRouteWithChildren,
  SessionTenantTeamNewRoute: SessionTenantTeamNewRoute,
  SessionTenantExploreAppsSlugRoute: SessionTenantExploreAppsSlugRoute,
}

const SessionTenantRouteWithChildren = SessionTenantRoute._addFileChildren(
  SessionTenantRouteChildren,
)

interface SessionAccountRouteChildren {
  SessionAccountAuthorizationsRoute: typeof SessionAccountAuthorizationsRoute
  SessionAccountOnboardingRoute: typeof SessionAccountOnboardingRoute
  SessionAccountOrganizationsRoute: typeof SessionAccountOrganizationsRoute
  SessionAccountProfileRoute: typeof SessionAccountProfileRoute
}

const SessionAccountRouteChildren: SessionAccountRouteChildren = {
  SessionAccountAuthorizationsRoute: SessionAccountAuthorizationsRoute,
  SessionAccountOnboardingRoute: SessionAccountOnboardingRoute,
  SessionAccountOrganizationsRoute: SessionAccountOrganizationsRoute,
  SessionAccountProfileRoute: SessionAccountProfileRoute,
}

const SessionAccountRouteWithChildren = SessionAccountRoute._addFileChildren(
  SessionAccountRouteChildren,
)

interface SessionRouteChildren {
  SessionChromeFreeRoute: typeof SessionChromeFreeRouteWithChildren
  SessionTenantRoute: typeof SessionTenantRouteWithChildren
  SessionAccountRoute: typeof SessionAccountRouteWithChildren
}

const SessionRouteChildren: SessionRouteChildren = {
  SessionChromeFreeRoute: SessionChromeFreeRouteWithChildren,
  SessionTenantRoute: SessionTenantRouteWithChildren,
  SessionAccountRoute: SessionAccountRouteWithChildren,
}

const SessionRouteWithChildren =
  SessionRoute._addFileChildren(SessionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  CliSessionRoute: CliSessionRouteWithChildren,
  SessionRoute: SessionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
