/**
 * Sitemap Index
 *
 * Aggregates all dynamic sitemaps into a single sitemap index.
 * Referenced by robots.txt as the canonical sitemap location.
 *
 * URL: /sitemap-index.xml
 *
 * Note: @astrojs/sitemap only covers prerendered pages (none in this SSR app).
 * All dynamic content sitemaps are generated by custom API routes.
 */

import type { APIRoute } from "astro";

const TEDIX_BASE_DOMAINS = ["tedix.dev"];

function isTedixBaseDomain(hostname: string): boolean {
	return TEDIX_BASE_DOMAINS.some(
		(d) => hostname === d || hostname === `www.${d}`,
	);
}

export const GET: APIRoute = async ({ request }) => {
	const url = new URL(request.url);
	const baseUrl = url.origin;
	const hostname = url.hostname;
	const now = new Date().toISOString().split("T")[0];

	// App catalog sitemap only on tedix base domains, not customer CMS subdomains.
	const sitemaps = isTedixBaseDomain(hostname)
		? [
				{ loc: `${baseUrl}/sitemap-pages.xml`, lastmod: now },
				{ loc: `${baseUrl}/sitemap-apps.xml`, lastmod: now },
				{ loc: "https://tedix.dev/sitemap-posts.xml", lastmod: now },
			]
		: [];

	const entries = sitemaps
		.map(
			(s) => `
  <sitemap>
    <loc>${s.loc}</loc>
    <lastmod>${s.lastmod}</lastmod>
  </sitemap>`,
		)
		.join("");

	const sitemapIndex = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  ${entries}
</sitemapindex>`;

	return new Response(sitemapIndex.trim(), {
		status: 200,
		headers: {
			"Content-Type": "application/xml",
			"Cache-Control": "public, max-age=3600",
		},
	});
};
