/**
 * node_modules backup/restore (Sandbox SDK createBackup/restoreBackup).
 *
 * `bun install` refreshes dependencies for every CMS theme deploy. These
 * helpers back up the attempt-private node_modules directory and can restore
 * an equivalent archive into a later attempt's private directory. The key is
 * a content fingerprint of package.json + bun.lock; `bun install` still
 * verifies the restored dependency set before Astro builds.
 *
 * Correctness guarantees this must not weaken:
 *   - .vite/.astro/dist are wiped in the private attempt before install.
 *   - Any backup/restore failure must fall through to the caller's normal
 *     from-scratch `bun install` — never fail the deploy over a cache miss.
 *
 * Kept in its own module (no `cloudflare:workers` import, mirroring
 * `build-runner.ts`) so it can be unit-tested under the plain-node vitest
 * config apps/cms uses — deploy-workflow.ts itself imports `WorkflowEntrypoint`
 * from `cloudflare:workers` and can't be loaded outside a Workers runtime.
 */

import type { DirectoryBackupRecord } from "@cloudflare/sandbox";
import type { CmsSandbox } from "../sandbox";
import { errorMessage } from "@tedix/worker-kit/error-message";

type BackupSandboxClient = Pick<
	CmsSandbox,
	"exec" | "createBackup" | "restoreBackup"
>;

const NODE_MODULES_BACKUP_TTL_SECONDS = 7 * 24 * 60 * 60; // 7 days

function assertWorkspace(workspace: string): void {
	if (
		workspace !== "/workspace" &&
		!/^\/tmp\/tedix-cms-deploy-[0-9a-f-]{36}$/.test(workspace)
	) {
		throw new Error("Invalid CMS dependency workspace");
	}
}

function nodeModulesBackupKey(
	templateSlug: string,
	fingerprint: string,
): string {
	return `node-modules-backups/${templateSlug}/${fingerprint}.json`;
}

/**
 * Content fingerprint of the resolved dependency set for the workspace as it
 * stands right now (i.e. after any template overlay has already run). Returns
 * null on any failure — callers must treat that as "no cache available",
 * never as a hard error.
 */
export async function computeNodeModulesFingerprint(
	sandbox: BackupSandboxClient,
	workspace = "/workspace",
): Promise<string | null> {
	try {
		assertWorkspace(workspace);
		const result = await (
			await sandbox.exec([
				"bash",
				"-lc",
				`cat '${workspace}/package.json' '${workspace}/bun.lock' 2>/dev/null | sha256sum | cut -d' ' -f1`,
			])
		).output({ encoding: "utf8", maxBytes: 16 * 1024 * 1024 });
		const hash = result.stdout.trim();
		if (
			result.exitCode !== 0 ||
			result.timedOut ||
			result.signal !== undefined ||
			result.truncated ||
			!/^[0-9a-f]{64}$/.test(hash)
		)
			return null;
		return hash;
	} catch {
		return null;
	}
}

/**
 * Attempt to restore a previously-backed-up node_modules for this exact
 * template + dependency fingerprint. Never throws — any failure (missing
 * key, expired/garbage-collected backup, restore error) is reported as a
 * miss so the caller falls through to a normal `bun install`.
 */
export async function restoreNodeModulesBackup(
	sandbox: BackupSandboxClient,
	storage: R2Bucket,
	templateSlug: string,
	workspace = "/workspace",
): Promise<{ hit: boolean; fingerprint: string | null; reason?: string }> {
	const fingerprint = await computeNodeModulesFingerprint(sandbox, workspace);
	if (!fingerprint) {
		return { hit: false, fingerprint: null, reason: "fingerprint-unavailable" };
	}
	try {
		const obj = await storage.get(
			nodeModulesBackupKey(templateSlug, fingerprint),
		);
		if (!obj) return { hit: false, fingerprint, reason: "no-backup-recorded" };
		const backup = await obj.json<DirectoryBackupRecord>();
		const result = await sandbox.restoreBackup({
			...backup,
			dir: `${workspace}/node_modules`,
		});
		if (!result.success) {
			return { hit: false, fingerprint, reason: "restore-reported-failure" };
		}
		return { hit: true, fingerprint };
	} catch (err) {
		return { hit: false, fingerprint, reason: errorMessage(err) };
	}
}

/**
 * Snapshot the freshly-installed /workspace/node_modules so a later build
 * with the same template + dependency fingerprint can restore instead of
 * reinstalling. Best-effort — failures are swallowed; a missed backup just
 * means the next build falls back to a normal install, not a broken one.
 */
export async function saveNodeModulesBackup(
	sandbox: BackupSandboxClient,
	storage: R2Bucket,
	templateSlug: string,
	fingerprint: string,
	workspace = "/workspace",
): Promise<boolean> {
	try {
		assertWorkspace(workspace);
		const backup = await sandbox.createBackup({
			dir: `${workspace}/node_modules`,
			name: `node_modules-${templateSlug}-${fingerprint.slice(0, 12)}`,
			ttl: NODE_MODULES_BACKUP_TTL_SECONDS,
			// Defensive: .vite is never present at this point in the flow (it's
			// wiped before install and only regenerated by the Astro build step,
			// which runs later), but exclude it explicitly so a future reordering
			// can't silently bake a stale Vite cache into the snapshot.
			excludes: [".vite"],
		});
		await storage.put(
			nodeModulesBackupKey(templateSlug, fingerprint),
			JSON.stringify(backup),
		);
		return true;
	} catch {
		return false;
	}
}
