// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type {
	BylineSummary,
	ContentBylineCredit,
	TaxonomyTerm,
	PortableTextBlock,
} from "emdash";

export interface Post {
	id: string;
	slug: string | null;
	status: string;
	title: string;
	featured_image?: {
		id: string;
		src?: string;
		alt?: string;
		width?: number;
		height?: number;
		filename?: string;
		mimeType?: string;
		blurhash?: string;
		dominantColor?: string;
		focalX?: number;
		focalY?: number;
		provider?: string;
		previewUrl?: string;
		meta?: Record<string, unknown>;
		darkVariant?: {
			id: string;
			src?: string;
			alt?: string;
			width?: number;
			height?: number;
			filename?: string;
			mimeType?: string;
			blurhash?: string;
			dominantColor?: string;
			focalX?: number;
			focalY?: number;
			provider?: string;
			previewUrl?: string;
			meta?: Record<string, unknown>;
		};
	};
	content?: PortableTextBlock[];
	excerpt?: string;
	createdAt: Date;
	updatedAt: Date;
	publishedAt: Date | null;
	byline?: BylineSummary | null;
	bylines?: ContentBylineCredit[];
	terms?: Record<string, TaxonomyTerm[]>;
}

export interface PageContentMarketingProseV1Block {
	_type: "marketing_prose";
	_version: 1;
	_key: string;
	body: PortableTextBlock[];
}

export type PageContentMarketingProseBlock = PageContentMarketingProseV1Block;

export interface PageContentMarketingHeroV1Block {
	_type: "marketing_hero";
	_version: 1;
	_key: string;
	headline: string;
	subheadline?: string | null;
	primary_cta_label?: string | null;
	primary_cta_url?: string | null;
	secondary_cta_label?: string | null;
	secondary_cta_url?: string | null;
	image_url?: string | null;
}

export interface PageContentMarketingHeroV2Block {
	_type: "marketing_hero";
	_version: 2;
	_key: string;
	headline: string;
	subheadline?: string | null;
	primary_cta_label?: string | null;
	primary_cta_url?: string | null;
	secondary_cta_label?: string | null;
	secondary_cta_url?: string | null;
	image?: {
		id: string;
		src?: string;
		alt?: string;
		width?: number;
		height?: number;
		filename?: string;
		mimeType?: string;
		blurhash?: string;
		dominantColor?: string;
		focalX?: number;
		focalY?: number;
		provider?: string;
		previewUrl?: string;
		meta?: Record<string, unknown>;
		darkVariant?: {
			id: string;
			src?: string;
			alt?: string;
			width?: number;
			height?: number;
			filename?: string;
			mimeType?: string;
			blurhash?: string;
			dominantColor?: string;
			focalX?: number;
			focalY?: number;
			provider?: string;
			previewUrl?: string;
			meta?: Record<string, unknown>;
		};
	} | null;
}

export type PageContentMarketingHeroBlock =
	| PageContentMarketingHeroV1Block
	| PageContentMarketingHeroV2Block;

export interface PageContentMarketingLogoStripV1Block {
	_type: "marketing_logo_strip";
	_version: 1;
	_key: string;
	eyebrow?: string | null;
	items?:
		| { url?: string | null; alt?: string | null; href?: string | null }[]
		| null;
}

export interface PageContentMarketingLogoStripV2Block {
	_type: "marketing_logo_strip";
	_version: 2;
	_key: string;
	eyebrow?: string | null;
	items?:
		| {
				image?: {
					id: string;
					src?: string;
					alt?: string;
					width?: number;
					height?: number;
					filename?: string;
					mimeType?: string;
					blurhash?: string;
					dominantColor?: string;
					focalX?: number;
					focalY?: number;
					provider?: string;
					previewUrl?: string;
					meta?: Record<string, unknown>;
					darkVariant?: {
						id: string;
						src?: string;
						alt?: string;
						width?: number;
						height?: number;
						filename?: string;
						mimeType?: string;
						blurhash?: string;
						dominantColor?: string;
						focalX?: number;
						focalY?: number;
						provider?: string;
						previewUrl?: string;
						meta?: Record<string, unknown>;
					};
				} | null;
				href?: string | null;
		  }[]
		| null;
}

export type PageContentMarketingLogoStripBlock =
	| PageContentMarketingLogoStripV1Block
	| PageContentMarketingLogoStripV2Block;

export interface PageContentMarketingFeaturesV1Block {
	_type: "marketing_features";
	_version: 1;
	_key: string;
	heading?: string | null;
	intro?: string | null;
	items?:
		| { title?: string | null; body?: string | null; href?: string | null }[]
		| null;
}

export type PageContentMarketingFeaturesBlock =
	PageContentMarketingFeaturesV1Block;

export interface PageContentMarketingStatsV1Block {
	_type: "marketing_stats";
	_version: 1;
	_key: string;
	heading?: string | null;
	items?: { value?: string | null; label?: string | null }[] | null;
}

export type PageContentMarketingStatsBlock = PageContentMarketingStatsV1Block;

export interface PageContentMarketingCtaV1Block {
	_type: "marketing_cta";
	_version: 1;
	_key: string;
	headline?: string | null;
	body?: string | null;
	cta_label?: string | null;
	cta_url?: string | null;
	image_url?: string | null;
}

export interface PageContentMarketingCtaV2Block {
	_type: "marketing_cta";
	_version: 2;
	_key: string;
	headline?: string | null;
	body?: string | null;
	cta_label?: string | null;
	cta_url?: string | null;
	image?: {
		id: string;
		src?: string;
		alt?: string;
		width?: number;
		height?: number;
		filename?: string;
		mimeType?: string;
		blurhash?: string;
		dominantColor?: string;
		focalX?: number;
		focalY?: number;
		provider?: string;
		previewUrl?: string;
		meta?: Record<string, unknown>;
		darkVariant?: {
			id: string;
			src?: string;
			alt?: string;
			width?: number;
			height?: number;
			filename?: string;
			mimeType?: string;
			blurhash?: string;
			dominantColor?: string;
			focalX?: number;
			focalY?: number;
			provider?: string;
			previewUrl?: string;
			meta?: Record<string, unknown>;
		};
	} | null;
}

export type PageContentMarketingCtaBlock =
	| PageContentMarketingCtaV1Block
	| PageContentMarketingCtaV2Block;

export interface PageContentMarketingTextWithImageV1Block {
	_type: "marketing_text_with_image";
	_version: 1;
	_key: string;
	heading?: string | null;
	body?: string | null;
	image_url?: string | null;
	image_side?: "left" | "right" | null;
	cta_label?: string | null;
	cta_url?: string | null;
}

export interface PageContentMarketingTextWithImageV2Block {
	_type: "marketing_text_with_image";
	_version: 2;
	_key: string;
	heading?: string | null;
	body?: string | null;
	image?: {
		id: string;
		src?: string;
		alt?: string;
		width?: number;
		height?: number;
		filename?: string;
		mimeType?: string;
		blurhash?: string;
		dominantColor?: string;
		focalX?: number;
		focalY?: number;
		provider?: string;
		previewUrl?: string;
		meta?: Record<string, unknown>;
		darkVariant?: {
			id: string;
			src?: string;
			alt?: string;
			width?: number;
			height?: number;
			filename?: string;
			mimeType?: string;
			blurhash?: string;
			dominantColor?: string;
			focalX?: number;
			focalY?: number;
			provider?: string;
			previewUrl?: string;
			meta?: Record<string, unknown>;
		};
	} | null;
	image_side?: "left" | "right" | null;
	cta_label?: string | null;
	cta_url?: string | null;
}

export type PageContentMarketingTextWithImageBlock =
	| PageContentMarketingTextWithImageV1Block
	| PageContentMarketingTextWithImageV2Block;

export interface PageContentMarketingTestimonialsV1Block {
	_type: "marketing_testimonials";
	_version: 1;
	_key: string;
	headline?: string | null;
	items?:
		| {
				quote?: string | null;
				author?: string | null;
				role?: string | null;
				company?: string | null;
				avatar?: string | null;
		  }[]
		| null;
}

export interface PageContentMarketingTestimonialsV2Block {
	_type: "marketing_testimonials";
	_version: 2;
	_key: string;
	headline?: string | null;
	items?:
		| {
				quote?: string | null;
				author?: string | null;
				role?: string | null;
				company?: string | null;
				avatar?: {
					id: string;
					src?: string;
					alt?: string;
					width?: number;
					height?: number;
					filename?: string;
					mimeType?: string;
					blurhash?: string;
					dominantColor?: string;
					focalX?: number;
					focalY?: number;
					provider?: string;
					previewUrl?: string;
					meta?: Record<string, unknown>;
					darkVariant?: {
						id: string;
						src?: string;
						alt?: string;
						width?: number;
						height?: number;
						filename?: string;
						mimeType?: string;
						blurhash?: string;
						dominantColor?: string;
						focalX?: number;
						focalY?: number;
						provider?: string;
						previewUrl?: string;
						meta?: Record<string, unknown>;
					};
				} | null;
		  }[]
		| null;
}

export type PageContentMarketingTestimonialsBlock =
	| PageContentMarketingTestimonialsV1Block
	| PageContentMarketingTestimonialsV2Block;

export interface PageContentMarketingPricingV1Block {
	_type: "marketing_pricing";
	_version: 1;
	_key: string;
	headline?: string | null;
	plans?:
		| {
				name?: string | null;
				price?: string | null;
				period?: string | null;
				description?: string | null;
				features?: string | null;
				cta_label?: string | null;
				cta_url?: string | null;
				highlighted?: boolean | null;
		  }[]
		| null;
}

export type PageContentMarketingPricingBlock =
	PageContentMarketingPricingV1Block;

export interface PageContentMarketingFaqV1Block {
	_type: "marketing_faq";
	_version: 1;
	_key: string;
	headline?: string | null;
	items?: { question?: string | null; answer?: string | null }[] | null;
}

export type PageContentMarketingFaqBlock = PageContentMarketingFaqV1Block;

export type PageContentBlock =
	| PageContentMarketingProseBlock
	| PageContentMarketingHeroBlock
	| PageContentMarketingLogoStripBlock
	| PageContentMarketingFeaturesBlock
	| PageContentMarketingStatsBlock
	| PageContentMarketingCtaBlock
	| PageContentMarketingTextWithImageBlock
	| PageContentMarketingTestimonialsBlock
	| PageContentMarketingPricingBlock
	| PageContentMarketingFaqBlock;

export interface Page {
	id: string;
	slug: string | null;
	status: string;
	title: string;
	meta_description?: string;
	content?: PageContentBlock[];
	createdAt: Date;
	updatedAt: Date;
	publishedAt: Date | null;
	byline?: BylineSummary | null;
	bylines?: ContentBylineCredit[];
	terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
	interface EmDashCollections {
		posts: Post;
		pages: Page;
	}
}
