DROP INDEX IF EXISTS `idx_app_adapters_app`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_capability_links_capability`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_org_capabilities_org`;--> statement-breakpoint
DROP INDEX IF EXISTS `health_history_app_idx`;--> statement-breakpoint
DROP INDEX IF EXISTS `mcp_prompts_app_idx`;--> statement-breakpoint
DROP INDEX IF EXISTS `mcp_resource_tpl_app_idx`;--> statement-breakpoint
DROP INDEX IF EXISTS `mcp_resources_app_idx`;--> statement-breakpoint
DROP INDEX IF EXISTS `mcp_tools_app_idx`;--> statement-breakpoint
DROP INDEX IF EXISTS `store_listings_app_idx`;--> statement-breakpoint
DROP INDEX IF EXISTS `store_listings_source_idx`;--> statement-breakpoint
DROP INDEX IF EXISTS `tool_tests_app_idx`;--> statement-breakpoint
DROP INDEX IF EXISTS `tool_tests_tool_idx`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_role_templates_org`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_tedi_session_states_tedi_user`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_call_costs_tedi`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_tedi_devices_tedi`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_tedi_runtime_snapshots_tedi`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_tedi_usage_events_tedi`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_app_tools_app`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_work_item_corroboration_item`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_work_item_executor_checkouts_org`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_work_item_projections_work_item`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_work_item_relations_from`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_workstations_org`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_approval_requests_org`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_approval_requests_tedi`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_knowledge_entries_org`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_skill_entries_org`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_skill_run_artifacts_run`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_muscle_memory_tedi`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_workspace_edits_tedi`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_kernel_conversation_grants_conversation`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_kernel_runtime_events_run`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_tedi_runtime_events_run`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_tedi_cron_executions_org`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_rationale_tedi`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_objectives_tedi`;--> statement-breakpoint
DROP INDEX IF EXISTS `idx_tasks_tedi`;