#!/usr/bin/env bun
/**
 * Generate src/template-snapshot.ts — a static map of canonical
 * starter-template files used by the Site Builder Worker at MCP runtime
 * for the theme_resync_template + theme_diff_template tools.
 *
 * The Site Builder Worker can't `git pull` at runtime, so we bundle the
 * canonical starter into the Worker module graph as inlined strings.
 * Wrangler picks up the regular TS import like any other source file.
 *
 * Source dirs: `apps/cms/templates/{tedix,marketing}/` — the starter
 * directories staged into the Site Builder sandbox image under
 * `/workspace-templates/`. `tedix` remains the default seeded into
 * `/workspace`; `marketing` is an additive starter selected per-tenant
 * via `templateSlug`.
 *
 * Scope: every locked file + every editable scaffold file enumerated
 * in `src/template-policy.ts`. The template bun.lock must be included so
 * persistent sandboxes cannot pair a current package.json with an old lock.
 * Unlisted files such as node_modules are skipped.
 *
 * Re-run via `bun run snapshot:template`. Idempotent — overwrites the
 * snapshot file. Pass `--check` to compare the generated bytes with the
 * committed snapshot without writing. Warns (does not fail) if a constraints
 * path is missing on disk, so the studio can still ship while paths are in
 * flux.
 */

import { readFile, readdir, stat, writeFile } from "node:fs/promises";
import { dirname, extname, posix, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
	CMS_TEMPLATE_SLUGS as TEMPLATE_SLUGS,
	type CmsTemplateSlug as TemplateSlug,
	EDITABLE_FILES,
	EDITABLE_DIRS,
	LOCKED_FILES,
	lockedFilesForTemplate,
	lockedDirsForTemplate,
} from "../src/template-policy";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const OUT_FILE = resolve(ROOT, "src", "template-snapshot.ts");
const CHECK_ONLY = process.argv.includes("--check");

function templateDirFor(slug: TemplateSlug): string {
	return resolve(ROOT, "templates", slug);
}

const MARKETING_EDITABLE_SCAFFOLDS = ["src/pages/kontakt.astro"];
const SNAPSHOT_SOURCE_EXTENSIONS = new Set([
	".astro",
	".css",
	".ts",
	".tsx",
	".json",
	".js",
	".mjs",
	".svg",
]);

// A few extra known starter scaffolds worth preserving in resync. Add only
// non-locked, non-editable scaffolds that ship in the template.
const EXTRA_SCAFFOLDS = [
	"LICENSE",
	"UPSTREAM.md",
	"seed/seed.json",
	"emdash-env.d.ts",
	// Typed-section landing-page renderer — handles the `sections` JSON field
	// (9 section types: hero, textImage, cardGrid, stats, ctaBand, logoStrip,
	// video, richText, form). New marketing tenants get this built-in; no
	// per-tenant [slug].astro hand-authoring required.
	"src/pages/[slug].astro",
	// Native versioned-block renderer imported by both marketing page routes.
	"src/components/MarketingBlocks.astro",
	"src/components/NativeMarketingBlock.astro",
	"src/components/NativePage.astro",
	"src/components/NativePageBlock.astro",
	"src/components/FaqSection.astro",
	"src/components/FaqBlock.astro",
	// Shared posts listing implementation imported by the locked
	// src/pages/posts/index.astro route.
	"src/components/PostIndexPage.astro",
	// Starter components.
	// Editable; vibe agents may customize. Shipped in v7.
	"src/components/HeroSection.astro",
	"src/components/ComparisonTable.astro",
	"src/components/LeadCaptureForm.astro",
	"src/components/PricingBlock.astro",
	"src/components/AuthorByline.astro",
	// Official oRPC v2 transport shared by the inlined platform plugins.
	"src/lib/platform-rpc.ts",
	// In-repo trusted Emdash plugin: SEO/AEO emission. Wired via the
	// (locked) astro.config.mjs `plugins` option. Shipped to every
	// sandbox via theme_resync_template alongside the locked config.
	"src/plugins/tedix-seo-aeo/index.ts",
	"src/plugins/tedix-page-search/index.ts",
	"src/plugins/tedix-homepage-policy/index.ts",
	// In-repo trusted Emdash plugin: tedi-bridge. Posts publish events
	// into the org's Tedix platform brain via /rpc/memory/learn. Wired
	// in the (locked) astro.config.mjs alongside tedix-seo-aeo. Reads
	// per-org settings (`tedi.platformApiKey`, `tedi.id`, ...) from
	// Emdash settings KV.
	"src/plugins/tedix-tedi-bridge/index.ts",
	// In-repo trusted Emdash plugin: newsletter. Double-opt-in subscribe +
	// confirm + unsubscribe routes + content:afterPublish digest fan-out.
	// Outbound mail goes via the platform `tediEmail.sendEmail` endpoint
	// (Resend → CF fallback). Wired in astro.config.mjs alongside the
	// other trusted plugins.
	"src/plugins/emdash-newsletter/index.ts",
	// Newsletter signup block — companion to the newsletter plugin.
	// Posts to the plugin's subscribe route with email + source.
	"src/components/Newsletter.astro",
	// Native Emdash admin plugin: Site Builder tab + CMS launcher widget.
	// Embeds a live preview iframe and links to builder.tedix.dev from the
	// Emdash admin. Both files are locked — the plugin is infrastructure,
	// not user-editable content. Two files: plugin definition + admin React module.
	"src/plugins/tedix-site-builder/index.ts",
	"src/plugins/tedix-site-builder/admin.tsx",
];

const SHARED_LOCKED_FILES = new Set<string>(LOCKED_FILES);

async function exists(path: string): Promise<boolean> {
	try {
		await stat(path);
		return true;
	} catch {
		return false;
	}
}

async function loadEntry(
	templateDir: string,
	rel: string,
): Promise<{ rel: string; content: string } | null> {
	const abs = resolve(templateDir, rel);
	if (!(await exists(abs))) return null;
	const content = await readFile(abs, "utf8");
	return { rel, content };
}

async function collectDirectoryFiles(
	templateDir: string,
	relDir: string,
): Promise<string[]> {
	const absDir = resolve(templateDir, relDir);
	if (!(await exists(absDir))) return [];
	const files: string[] = [];
	for (const entry of await readdir(absDir, { withFileTypes: true })) {
		if (entry.name.startsWith(".") || entry.name.endsWith("~")) continue;
		const rel = `${relDir}${entry.name}`;
		if (entry.isDirectory()) {
			files.push(...(await collectDirectoryFiles(templateDir, `${rel}/`)));
		} else if (
			(entry.isFile() ||
				(entry.isSymbolicLink() &&
					(await stat(resolve(templateDir, rel))).isFile())) &&
			SNAPSHOT_SOURCE_EXTENSIONS.has(extname(entry.name))
		) {
			files.push(rel);
		}
	}
	return files.sort();
}

async function collectTemplateEntries(
	slug: TemplateSlug,
): Promise<Array<{ rel: string; content: string }>> {
	const templateDir = templateDirFor(slug);
	const lockedFiles = lockedFilesForTemplate(slug);
	const lockedDirs = lockedDirsForTemplate(slug);
	const missingLockedDirs = (
		await Promise.all(
			lockedDirs.map(async (dir) =>
				(await exists(resolve(templateDir, dir))) ? null : dir,
			),
		)
	).filter((dir): dir is string => dir !== null);
	if (missingLockedDirs.length > 0) {
		throw new Error(
			`Template "${slug}" is missing locked directories: ${missingLockedDirs.join(", ")}`,
		);
	}
	const lockedDirectoryFiles = (
		await Promise.all(
			lockedDirs.map((dir) => collectDirectoryFiles(templateDir, dir)),
		)
	).flat();
	const editableDirectoryFiles = (
		await Promise.all(
			EDITABLE_DIRS.map((dir) => collectDirectoryFiles(templateDir, dir)),
		)
	).flat();
	const candidates = [
		...new Set([
			...lockedFiles,
			...lockedDirectoryFiles,
			...editableDirectoryFiles,
			...EDITABLE_FILES,
			...EXTRA_SCAFFOLDS,
			...(slug === "marketing" ? MARKETING_EDITABLE_SCAFFOLDS : []),
		]),
	].sort();
	const entries: Array<{ rel: string; content: string }> = [];
	const missingLocked: string[] = [];

	for (const rel of candidates) {
		let entry = await loadEntry(templateDir, rel);
		if (!entry && slug === "marketing" && SHARED_LOCKED_FILES.has(rel)) {
			entry = await loadEntry(templateDirFor("tedix"), rel);
		}
		if (entry) {
			entries.push(entry);
		} else if (lockedFiles.includes(rel)) {
			// Locked file expected but absent — likely a constraints/template drift.
			missingLocked.push(rel);
		}
	}

	if (missingLocked.length > 0) {
		// Emit a warning but continue — the studio still ships, the diff tool
		// just won't have a baseline for these paths.
		console.warn(
			`[generate-template-snapshot] WARNING (${slug}): locked files in constraints.ts missing on disk:\n  - ${missingLocked.join("\n  - ")}`,
		);
	}

	return entries;
}

function assertRelativeImportsResolve(
	slug: TemplateSlug,
	entries: Array<{ rel: string; content: string }>,
): void {
	const paths = new Set(entries.map((entry) => entry.rel));
	const missing: string[] = [];
	for (const { rel, content } of entries) {
		if (!SNAPSHOT_SOURCE_EXTENSIONS.has(extname(rel))) continue;
		for (const match of content.matchAll(
			/\b(?:import|export)\s+(?:[^;]*?\s+from\s+)?["'](\.{1,2}\/[^"']+)["']/g,
		)) {
			const target = posix.normalize(posix.join(posix.dirname(rel), match[1]!));
			const candidates = [
				target,
				...([".astro", ".ts", ".tsx", ".js", ".mjs", ".d.ts"] as const).map(
					(extension) => `${target}${extension}`,
				),
				`${target}/index.ts`,
			];
			if (!candidates.some((candidate) => paths.has(candidate))) {
				missing.push(`${rel} -> ${match[1]}`);
			}
		}
	}
	if (missing.length > 0) {
		throw new Error(
			`Template "${slug}" snapshot omits relative imports:\n  - ${missing.join("\n  - ")}`,
		);
	}
}

/** Encode one template's entries as a JS object literal body. */
function renderRecord(
	entries: Array<{ rel: string; content: string }>,
	indent: string,
): string {
	return entries
		.map(({ rel, content }) => {
			// Use JSON.stringify to safely encode the file content as a JS string.
			// Wrangler/esbuild handles huge string literals fine.
			return `${indent}${JSON.stringify(rel)}: ${JSON.stringify(content)},`;
		})
		.join("\n");
}

async function main(): Promise<void> {
	const perTemplate: Record<
		TemplateSlug,
		Array<{ rel: string; content: string }>
	> = {} as Record<TemplateSlug, Array<{ rel: string; content: string }>>;
	for (const slug of TEMPLATE_SLUGS) {
		perTemplate[slug] = await collectTemplateEntries(slug);
		assertRelativeImportsResolve(slug, perTemplate[slug]);
	}

	const header = `// AUTO-GENERATED by scripts/generate-template-snapshot.ts.
// DO NOT EDIT BY HAND. Run \`bun run snapshot:template\` to refresh.
// Source: apps/cms/templates/{${TEMPLATE_SLUGS.join(",")}}/**
//
// Consumed by theme_resync_template + theme_diff_template MCP tools and
// the deploy workflow's templateSlug-aware preflight resync.
`;

	// TEMPLATE_SNAPSHOTS — one frozen record per template slug.
	const snapshotBlocks = TEMPLATE_SLUGS.map((slug) => {
		const record = renderRecord(perTemplate[slug], "\t\t");
		return `\t${JSON.stringify(slug)}: Object.freeze({\n${record}\n\t}),`;
	}).join("\n");

	const body = `${header}
export const TEMPLATE_SNAPSHOTS: Readonly<
	Record<string, Readonly<Record<string, string>>>
> = Object.freeze({
${snapshotBlocks}
});

export const TEMPLATE_SNAPSHOT_PATHS_BY_TEMPLATE: Readonly<
	Record<string, readonly string[]>
> = Object.freeze({
${TEMPLATE_SLUGS.map((slug) => `\t${JSON.stringify(slug)}: Object.freeze(${JSON.stringify(perTemplate[slug].map((e) => e.rel).sort())}),`).join("\n")}
});
`;

	if (CHECK_ONLY) {
		const current = await readFile(OUT_FILE, "utf8").catch(() => null);
		if (current !== body) {
			throw new Error(
				"src/template-snapshot.ts is stale; run `bun run snapshot:template` and commit the result",
			);
		}
	} else {
		await writeFile(OUT_FILE, body, "utf8");
	}
	for (const slug of TEMPLATE_SLUGS) {
		const entries = perTemplate[slug];
		const totalBytes = entries.reduce((acc, e) => acc + e.content.length, 0);
		console.log(
			`[generate-template-snapshot] ${slug}: ${entries.length} files (${totalBytes} bytes)`,
		);
	}
	console.log(
		`[generate-template-snapshot] ${CHECK_ONLY ? "checked" : "wrote"} → ${OUT_FILE.replace(ROOT, "apps/cms")}`,
	);
}

main().catch((err) => {
	console.error("[generate-template-snapshot] failed:", err);
	process.exit(1);
});
