/**
 * oRPC Cognitive Stack Router
 *
 * Thin namespace composition over cohesive knowledge, skill catalog,
 * governance, workflow-run, and muscle-memory handler slices.
 */
import { skipOutputValidation } from "../orpc";
import {
	knowledgeGet,
	knowledgeList,
	knowledgeOpine,
	knowledgeSynthesize,
} from "./cognitive-knowledge";
import {
	muscleCrystallize,
	muscleList,
	muscleRegister,
	muscleUsage,
} from "./cognitive-muscle";
import {
	skillsAuditLowQuality,
	skillsDelete,
	skillsFind,
	skillsGet,
	skillsGetForMcp,
	skillsImprove,
	skillsListByApp,
	skillsListByOrg,
	skillsListPromotionCandidates,
	skillsListSummariesByApps,
	skillsMove,
	skillsPreview,
	skillsPromote,
	skillsRecord,
	skillsRepair,
	skillsSweepDraftTtl,
	skillsUsage,
} from "./cognitive-skill-catalog";
import {
	skillsActivateWorkflowImprovement,
	skillsApplyWorkshop,
	skillsAuditToolCoverage,
	skillsInspectWorkflowImprovement,
	skillsInspectWorkshop,
	skillsMineCandidates,
	skillsPortfolioBalance,
	skillsProposeWorkflowImprovement,
	skillsProposeWorkshop,
	skillsQuarantineWorkshop,
	skillsRejectWorkshop,
	skillsReviseWorkshop,
	skillsValidate,
} from "./cognitive-skill-governance";
import {
	skillsApproveWorkflow,
	skillsCompareWorkflowRevisions,
	skillsGetRunArtifact,
	skillsGetWorkflowReliability,
	skillsGetWorkflowRevision,
	skillsInspectWorkflowRun,
	skillsListRunArtifacts,
	skillsListWorkflowRetryCandidates,
	skillsListWorkflowRevisions,
	skillsListWorkflowSchedules,
	skillsListWorkflowSteps,
	skillsListWorkflowToolCalls,
	skillsPauseWorkflow,
	skillsRejectWorkflow,
	skillsRestartWorkflow,
	skillsResumeWorkflow,
	skillsRevokeSkillRun,
	skillsRunWorkflow,
	skillsRecordRunEffectObservation,
	skillsGetRunUsefulness,
	skillsRunWorkflowCancel,
	skillsRunWorkflowHistory,
	skillsRunWorkflowSendEvent,
	skillsRunWorkflowStatus,
} from "./cognitive-skill-runs";
import { knowledgeOs, muscleOs, skillsOs } from "./cognitive-shared";

export const knowledgeContractRouter = knowledgeOs.router({
	synthesize: knowledgeSynthesize,
	opine: knowledgeOpine,
	list: skipOutputValidation(knowledgeList),
	get: skipOutputValidation(knowledgeGet),
});

export const skillsContractRouter = skillsOs.router({
	record: skillsRecord,
	improve: skillsImprove,
	proposeWorkshop: skillsProposeWorkshop,
	mineCandidates: skipOutputValidation(skillsMineCandidates),
	portfolioBalance: skipOutputValidation(skillsPortfolioBalance),
	proposeWorkflowImprovement: skillsProposeWorkflowImprovement,
	inspectWorkflowImprovement: skipOutputValidation(
		skillsInspectWorkflowImprovement,
	),
	activateWorkflowImprovement: skipOutputValidation(
		skillsActivateWorkflowImprovement,
	),
	inspectWorkshop: skipOutputValidation(skillsInspectWorkshop),
	reviseWorkshop: skillsReviseWorkshop,
	applyWorkshop: skipOutputValidation(skillsApplyWorkshop),
	rejectWorkshop: skillsRejectWorkshop,
	quarantineWorkshop: skillsQuarantineWorkshop,
	delete: skillsDelete,
	get: skipOutputValidation(skillsGet),
	move: skillsMove,
	listByOrg: skipOutputValidation(skillsListByOrg),
	find: skipOutputValidation(skillsFind),
	listByApp: skipOutputValidation(skillsListByApp),
	listSummariesByApps: skipOutputValidation(skillsListSummariesByApps),
	listPromotionCandidates: skipOutputValidation(skillsListPromotionCandidates),
	auditLowQuality: skipOutputValidation(skillsAuditLowQuality),
	sweepDraftTtl: skipOutputValidation(skillsSweepDraftTtl),
	getForMcp: skipOutputValidation(skillsGetForMcp),
	usage: skipOutputValidation(skillsUsage),
	validate: skillsValidate,
	auditToolCoverage: skipOutputValidation(skillsAuditToolCoverage),
	repair: skipOutputValidation(skillsRepair),
	promote: skipOutputValidation(skillsPromote),
	preview: skipOutputValidation(skillsPreview),
	runWorkflow: skillsRunWorkflow,
	recordRunEffectObservation: skillsRecordRunEffectObservation,
	getRunUsefulness: skillsGetRunUsefulness,
	runWorkflowStatus: skipOutputValidation(skillsRunWorkflowStatus),
	runWorkflowCancel: skillsRunWorkflowCancel,
	runWorkflowSendEvent: skillsRunWorkflowSendEvent,
	runWorkflowHistory: skillsRunWorkflowHistory,
	listWorkflowRetryCandidates: skillsListWorkflowRetryCandidates,
	inspectWorkflowRun: skipOutputValidation(skillsInspectWorkflowRun),
	listWorkflowSteps: skipOutputValidation(skillsListWorkflowSteps),
	listWorkflowToolCalls: skipOutputValidation(skillsListWorkflowToolCalls),
	listWorkflowRevisions: skipOutputValidation(skillsListWorkflowRevisions),
	getWorkflowRevision: skipOutputValidation(skillsGetWorkflowRevision),
	compareWorkflowRevisions: skipOutputValidation(
		skillsCompareWorkflowRevisions,
	),
	getWorkflowReliability: skipOutputValidation(skillsGetWorkflowReliability),
	listWorkflowSchedules: skillsListWorkflowSchedules,
	pauseWorkflow: skillsPauseWorkflow,
	resumeWorkflow: skillsResumeWorkflow,
	restartWorkflow: skillsRestartWorkflow,
	approveWorkflow: skillsApproveWorkflow,
	rejectWorkflow: skillsRejectWorkflow,
	getRunArtifact: skipOutputValidation(skillsGetRunArtifact),
	listRunArtifacts: skipOutputValidation(skillsListRunArtifacts),
	revokeSkillRun: skillsRevokeSkillRun,
});

export const muscleContractRouter = muscleOs.router({
	list: skipOutputValidation(muscleList),
	register: muscleRegister,
	crystallize: muscleCrystallize,
	usage: skipOutputValidation(muscleUsage),
});
