import {
	authorizeOwnedChannelProcedure,
	revokeOwnedChannelProcedure,
} from "./work-items/owned-channel";
/**
 * work-items router composition.
 * Capability handlers and shared policy live in ./work-items/.
 */
import {
	addRelationProcedure,
	corroborateProcedure,
	getByIdRoute,
	getOrgGraphHealthRoute,
	getWorkGraphHealthRoute,
	listActivityRoute,
	attachWorkItemSourceRoute,
	listProjectionsRoute,
	listWorkItemSourcesRoute,
	reconcileWorkItemSourcesRoute,
	listCorroborationsProcedure,
	listRelationsRoute,
	listRoute,
	runWorkGraphStewardRoute,
	upsertProjectionProcedure,
} from "./work-items/coordination-git";
import { createProcedure } from "./work-items/creation-reads";
import { addCommentProcedure } from "./work-items/lifecycle-marketing";
import {
	acceptProcedure,
	cancelFactoryWorkItemProcedure,
	completeProcedure,
	getReadinessProcedure,
	getAdmissionSpecificationProcedure,
	heartbeatAttemptProcedure,
	listAttemptsProcedure,
	listEventsProcedure,
	listEvidenceProcedure,
	previewEvidenceProcedure,
	settleAttemptProcedure,
	startAttemptProcedure,
	submitEvidenceProcedure,
	updateSpecificationProcedure,
	replaceAdmissionSpecificationProcedure,
	putResourcePoolProcedure,
	putBudgetEnvelopeProcedure,
	listResourcePoolsProcedure,
	listBudgetEnvelopesProcedure,
} from "./work-items/factory-lifecycle";
import { workItemsOs } from "./work-items/policy-helpers";
import {
	listAttemptProjectionProcedure,
	listReadinessProjectionProcedure,
	listRecoveryProjectionProcedure,
} from "./work-items/factory-projections";
import {
	addCaseDependencyProcedure,
	attachCaseWorkItemProcedure,
	createCaseProcedure,
	getCaseProcedure,
	listCasesProcedure,
	updateCaseProcedure,
} from "./work-items/cases";
import { inspectAttemptRepositoryProcedure } from "./work-items/workstation-inspection";

export const workItemsContractRouter = workItemsOs.router({
	authorizeOwnedChannel: authorizeOwnedChannelProcedure,
	revokeOwnedChannel: revokeOwnedChannelProcedure,
	create: createProcedure,
	list: listRoute,
	listReadinessProjection: listReadinessProjectionProcedure,
	createCase: createCaseProcedure,
	listCases: listCasesProcedure,
	getCase: getCaseProcedure,
	updateCase: updateCaseProcedure,
	attachCaseWorkItem: attachCaseWorkItemProcedure,
	addCaseDependency: addCaseDependencyProcedure,
	getById: getByIdRoute,
	getWorkGraphHealth: getWorkGraphHealthRoute,
	runWorkGraphSteward: runWorkGraphStewardRoute,
	getOrgGraphHealth: getOrgGraphHealthRoute,
	listRelations: listRelationsRoute,
	listActivity: listActivityRoute,
	listAttemptProjection: listAttemptProjectionProcedure,
	listRecoveryProjection: listRecoveryProjectionProcedure,
	attachWorkItemSource: attachWorkItemSourceRoute,
	listProjections: listProjectionsRoute,
	listWorkItemSources: listWorkItemSourcesRoute,
	reconcileWorkItemSources: reconcileWorkItemSourcesRoute,
	updateSpecification: updateSpecificationProcedure,
	replaceAdmissionSpecification: replaceAdmissionSpecificationProcedure,
	getAdmissionSpecification: getAdmissionSpecificationProcedure,
	putResourcePool: putResourcePoolProcedure,
	putBudgetEnvelope: putBudgetEnvelopeProcedure,
	listResourcePools: listResourcePoolsProcedure,
	listBudgetEnvelopes: listBudgetEnvelopesProcedure,
	accept: acceptProcedure,
	getReadiness: getReadinessProcedure,
	cancel: cancelFactoryWorkItemProcedure,
	complete: completeProcedure,
	addComment: addCommentProcedure,
	corroborate: corroborateProcedure,
	listCorroborations: listCorroborationsProcedure,
	addRelation: addRelationProcedure,
	startAttempt: startAttemptProcedure,
	heartbeatAttempt: heartbeatAttemptProcedure,
	settleAttempt: settleAttemptProcedure,
	listAttempts: listAttemptsProcedure,
	inspectAttemptRepository: inspectAttemptRepositoryProcedure,
	submitEvidence: submitEvidenceProcedure,
	listEvidence: listEvidenceProcedure,
	previewEvidence: previewEvidenceProcedure,
	listEvents: listEventsProcedure,
	upsertProjection: upsertProjectionProcedure,
});
